---
sidebar: sidebar 
permalink: concepts/architecture.html 
keywords: astra, astra datastore, architecture, deployment, astra data store, kubernetes, netapp, clusters, trident 
summary: アストラデータストアは、スタンドアロンの Kubernetes クラスタに導入できます。スタンドアロンの Kubernetes クラスタは、別のクラスタで実行されている Kubernetes アプリケーションに永続的ボリュームを提供します。 Kubernetes クラスタは、同じノードプールで他のアプリケーションをホストしたり、 Kubernetes クラスタで別のノードプールでアプリケーションをホストしたりすることもできます。 
---
= Astra データストア導入モデル
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


Astraデータストアは、Kubernetesと連携して導入およびオーケストレーションされたアプリケーションを使用して、ホスト上でストレージドライブを直接管理します。

次のいずれかの方法で、ベアメタルサーバまたは仮想サーバにAstraデータストアをインストールできます。

* スタンドアロンの専用 Kubernetes クラスタに導入して、別のクラスタ（スタンドアロンクラスタ）で実行されている Kubernetes アプリケーションに永続ボリュームを提供します。
* Kubernetes クラスタに導入し、同じノードプール（コンバージドクラスタ）で他のワークロードアプリケーションをホストすることもできます。
* Kubernetes クラスタに導入すると、他のワークロードアプリケーションも別のノードプール（分離型クラスタ）にホストできます。


link:../get-started/requirements.html["Astra Data Storeのハードウェア要件の詳細"]。

Astraデータストアは、Astra製品ファミリーの一部です。アストラファミリー全体の展望については、を参照してください https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra ファミリーの紹介"^]。



== Astra データストアエコシステム

Astraデータストアは次の機能を備えています。

* * Astra Control Center * ：オンプレミス環境で Kubernetes クラスタをアプリケーション対応で管理するために、 Astra Control Center ソフトウェアを使用。Kubernetes アプリケーションを簡単にバックアップし、データを別のクラスタに移行して、作業用アプリケーションのクローンを瞬時に作成できます。
+
Astra Control Centerは、ONTAP またはAstraデータストアストレージバックエンドを備えたAstra TridentストレージバックエンドでKubernetesクラスタをサポートします。

* * Trident * ：ネットアップが管理する、完全にサポートされているオープンソースのストレージプロビジョニングおよびオーケストレーションツールである Astra Trident を使用すると、 Docker と Kubernetes で管理されるコンテナ化アプリケーション用のストレージボリュームを作成できます。
+
Astra Tridentを使用して、Astraデータストアにボリュームを作成する。

* * Cloud Insights * ：ネットアップのクラウドインフラ監視ツールである Cloud Insights を使用すると、 Astra Control で管理された Kubernetes クラスタのパフォーマンスと利用率を監視できます。Cloud Insights ：ストレージ使用率とワークロードの相関関係を示します。
+
Cloud Insights 接続を Astra Control で有効にすると、 Astra Control の UI ページにテレメトリ情報が表示されます。Cloud Insights は、Astraデータストアで管理されているリソースに関する情報を表示します。





== Astra データストアインターフェイス

さまざまなインターフェイスを使用してタスクを完了できます。

* * Web ユーザーインターフェイス (UI) * ： Astra Control Service と Astra Control Center は、同じ Web ベースの UI を使用して、アプリケーションの管理、移行、保護を行うことができます。また、Astraデータストアボリュームに関する情報も表示されます。
* * API* ： Astra Control Service と Astra Control Center は、同じ Astra Control API を使用します。API を使用するタスクは、 UI を使用するタスクと同じです。Astra Control APIを使用して、Astraデータストアに関する情報を取得することもできます。
* *kubectlコマンド*: Astraデータストアを操作するには'kubectlコマンドを直接使用できます
* * Kubernetes拡張機能*：さらに、Astra Data Store Kubernetes API拡張機能を使用できます。
+
カスタムリソース定義（CRD）はKubernetes REST APIの拡張機能で、Astra Data Storeオペレータが導入されたときに作成されます。外部エンティティは、 Kubernetes API サーバを呼び出して SSD とやり取りします。Astraデータストアは、特定のSSDに対する更新を監視してから、内部のREST APIを呼び出します。





== を参照してください。

* https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra ファミリーの紹介"^]
* https://docs.netapp.com/us-en/astra/index.html["Astra Control Service のマニュアル"^]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center のドキュメント"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident のドキュメント"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API を使用"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

