---
sidebar: sidebar 
permalink: use/maintain-cluster.html 
keywords: astra, astra data store, kubectl 
summary: Astra データストアで kubectl コマンドを使用すると、クラスタを管理できます。 
---
= Astraデータストアクラスタを管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


クラスタを管理するには、Astraデータストアでkubectlコマンドを使用します。

* <<Add a node>>
* <<Remove a node>>
* <<Place a node in maintenance mode>>
* <<Add drives to a node>>
* <<Replace a drive>>


.必要なもの
* kubectl および kubectl-astras プラグインがインストールされたシステム。を参照してください link:../get-started/install-ads.html["Astra データストアをインストール"]。




== ノードを追加します

追加するノードは Kubernetes クラスタに含まれ、クラスタ内の他のノードと同様の設定である必要があります。


NOTE: Astra Control Centerを使用してノードを追加するには、を参照してください https://docs.netapp.com/us-en/astra-control-center/use/manage-backend.html["ストレージバックエンドクラスタにノードを追加します"^]。

.手順
. 新しいノードのdataIPがまだAstra Data StoreクラスタCRに含まれていない場合は、次の手順を実行します。
+
.. クラスタCRを編集し、「adsDataNetworks*Addresses *」フィールドにデータIPを追加します。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl edit astradscluster CLUSTER_NAME -n astrads-system
----
.. CR を保存します。
.. アストラデータストアクラスタにノードを追加します。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads nodes add --cluster CLUSTER_NAME
----


. それ以外の場合はノードを追加します。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads nodes add --cluster CLUSTER_NAME
----
. ノードが追加されたことを確認します。
+
[source, kubectl]
----
kubectl astrads nodes list
----




== ノードを削除します

クラスタ内のノードを削除するには、kubectlコマンドをAstraデータストアとともに使用します。

.手順
. すべてのノードを一覧表示します。
+
[source, kubectl]
----
kubectl astrads nodes list
----
+
対応：

+
[listing]
----
NODE NAME           NODE STATUS    CLUSTER NAME
sti-rx2540-534d...  Added       cluster-multinodes-21209
sti-rx2540-535d...  Added       cluster-multinodes-21209
...
----
. ノードを削除対象としてマークします。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads nodes remove NODE_NAME
----
+
対応：

+
[listing]
----
Removal label set on node sti-rx2540-534d.lab.org
Successfully updated ADS cluster cluster-multinodes-21209 desired node count from 4 to 3
----
+
ノードを削除対象としてマークすると'ノードのステータスはアクティブから現在の状態に変わります

. 削除したノードの現在のステータスを確認します
+
[source, kubectl]
----
kubectl get nodes --show-labels
----
+
対応：

+
[listing]
----
NAME                                            STATUS   ROLES                  AGE     VERSION   LABELS
sti-astramaster-050.lab.org   Ready    control-plane,master   3h39m   v1.20.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=sti-astramaster-050.lab.org,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node-role.kubernetes.io/master=
sti-rx2540-556a.lab.org       Ready    worker                 3h38m   v1.20.0   astrads.netapp.io/cluster=astrads-cluster-890c32c,astrads.netapp.io/storage-cluster-status=active,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=sti-rx2540-556a.lab.org,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
sti-rx2540-556b.lab.org       Ready    worker                 3h38m   v1.20.0   astrads.netapp.io/cluster=astrads-cluster-890c32c,astrads.netapp.io/storage-cluster-status=active,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=sti-rx2540-556b.lab.org,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
sti-rx2540-534d.lab.org       Ready    worker                 3h38m   v1.20.0   astrads.netapp.io/storage-cluster-status=present,astrads.netapp.io/storage-node-removal=,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=sti-rx2540-557a.lab.org,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
sti-rx2540-557b.lab.org       Ready    worker                 3h38m   v1.20.0   astrads.netapp.io/cluster=astrads-cluster-890c32c,astrads.netapp.io/storage-cluster-status=active,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=sti-rx2540-557b.lab.org,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
----
. ノードからAstraデータストアをアンインストールします。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads nodes uninstall NODE_NAME
----
. ノードがクラスタから削除されたことを確認します。
+
[source, kubectl]
----
kubectl astrads nodes list
----


ノードがAstraデータストアから削除される。



== ノードをメンテナンスモードにします

ホストのメンテナンスやパッケージのアップグレードが必要な場合は、ノードをメンテナンスモードにする必要があります。


NOTE: ノードがAstraデータストアクラスタにすでに含まれている必要があります。

ノードが保守モードのときは、クラスタにノードを追加できません。この例では、ノード「nhcitj1525」をメンテナンスモードにします。

.手順
. ノードの詳細を表示します。
+
[source, kubectl]
----
kubectl get nodes
----
+
対応：

+
[listing]
----
 NAME             STATUS   ROLES                  AGE     VERSION
 nhcitjj1525      Ready    <none>                 3d18h   v1.23.5
 nhcitjj1526      Ready    <none>                 3d18h   v1.23.5
 nhcitjj1527      Ready    <none>                 3d18h   v1.23.5
 nhcitjj1528      Ready    <none>                 3d18h   v1.23.5
 scs000039783-1   Ready    control-plane,master   3d18h   v1.23.5
----
. ノードがまだメンテナンスモードになっていないことを確認します。
+
[source, kubectl]
----
kubectl astrads maintenance list
----
+
応答（メンテナンスモードのノードがありません）：

+
[listing]
----
NAME    NODE NAME  IN MAINTENANCE  MAINTENANCE STATE       MAINTENANCE VARIANT
----
. メンテナンスモードを有効にします。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads maintenance create CR_NAME --node-name=NODE_NAME --variant=Node
----
+
例：

+
[source, kubectl]
----
kubectl astrads maintenance create maint1 --node-name="nhcitjj1525" --variant=Node
----
+
対応：

+
[listing]
----
Maintenance mode astrads-system/maint1 created
----
. ノードを一覧表示します。
+
[source, kubectl]
----
kubectl astrads nodes list
----
+
対応：

+
[listing]
----
NODE NAME       NODE STATUS     CLUSTER NAME
nhcitjj1525     Added           ftap-astra-012
...
----
. メンテナンスモードのステータスを確認します。
+
[source, kubectl]
----
kubectl astrads maintenance list
----
+
対応：

+
[listing]
----
NAME    NODE NAME       IN MAINTENANCE  MAINTENANCE STATE       MAINTENANCE VARIANT
node4   nhcitjj1525     true            ReadyForMaintenance     Node
----
+
保守モードの場合は 'false' として起動し 'true' に変更します「保守状態」が「準備期間の保守」から「 ReadyforMaintenance 」に変更されます。

. ノードのメンテナンスが完了したら、メンテナンスモードを無効にします。
+
[source, kubectl]
----
kubectl astrads maintenance update maint1 --node-name="nhcitjj1525" --variant=None
----
. ノードが保守モードでなくなったことを確認します。
+
[source, kubectl]
----
kubectl astrads maintenance list
----




== ノードにドライブを追加

Astraデータストアでkubectlコマンドを使用して、Astraデータストアクラスタ内のノードに物理ドライブまたは仮想ドライブを追加。

.必要なもの
* 次の条件を満たす1つ以上のドライブ：
+
** ノードに設置済み（物理ドライブ）またはノードVMに追加済み（仮想ドライブ）
** ドライブにパーティションがありません
** ドライブがクラスタで使用されていません
** クラスタ内のドライブの物理容量がライセンスで許可されている物理容量を超えない（たとえば、CPUコアあたり2TBのストレージをライセンスで付与すると、10ノードのクラスタの最大物理ドライブ容量は20TBになります）
** ドライブには、ノード内の他のアクティブドライブのサイズ以上が含まれています





NOTE: Astraデータストアのノードあたりのドライブ数は16本以下17台目のドライブを追加しようとすると、ドライブ追加要求は拒否されます。

.手順
. クラスタについて説明します。
+
[source, kubectl]
----
kubectl astrads clusters list
----
+
対応：

+
[listing]
----
CLUSTER NAME                    CLUSTER STATUS  NODE COUNT
cluster-multinodes-21209        created         4
----
. クラスタ名をメモします。
. クラスタ内のすべてのノードに追加できるドライブを表示します。cluster_nameをクラスタの名前に置き換えます。
+
[source, kubectl]
----
kubectl astrads adddrive show-available --cluster=CLUSTER_NAME
----
+
対応：

+
[listing]
----
Current cluster drive add status
Licensed cluster capacity: 72.0 TiB
Cluster capacity used: 2.3 TiB
Maximum node size without stranding: 800.0 GiB

Node: node1.name
Current node size: 600.0 GiB
Maximum licensed node size: 18.0 TiB
Total size that can be added to this node without stranding: 200.0 GiB
Add drive minimum/reccomended size: 100.0 GiB. Larger disks will be constrained to this size
NAME IDPATH SERIAL PARTITIONCOUNT SIZE ALREADYINCLUSTER
sdg /dev/disk/by-id/scsi-3c290e16d52479a9af5eac c290e16d52479a9af5eac 0 100 GiB false
sdh /dev/disk/by-id/scsi-3c2935798df68355dee0be c2935798df68355dee0be 0 100 GiB false

Node: node2.name
Current node size: 600.0 GiB
Maximum licensed node size: 18.0 TiB
Total size that can be added to this node without stranding: 200.0 GiB
Add drive minimum/reccomended size: 100.0 GiB. Larger disks will be constrained to this size
No suitable drives to add exist.


Node: node3.name
Current node size: 600.0 GiB
Maximum licensed node size: 18.0 TiB
Total size that can be added to this node without stranding: 200.0 GiB
Add drive minimum/reccomended size: 100.0 GiB. Larger disks will be constrained to this size
NAME IDPATH SERIAL PARTITIONCOUNT SIZE ALREADYINCLUSTER
sdg /dev/disk/by-id/scsi-3c29ee82992ed7a36fc942 c29ee82992ed7a36fc942 0 100 GiB false
sdh /dev/disk/by-id/scsi-3c29312aa362469fb3da9c c29312aa362469fb3da9c 0 100 GiB false

Node: node4.name
Current node size: 600.0 GiB
Maximum licensed node size: 18.0 TiB
Total size that can be added to this node without stranding: 200.0 GiB
Add drive minimum/reccomended size: 100.0 GiB. Larger disks will be constrained to this size
No suitable drives to add exist.
----
. 次のいずれかを実行します。
+
** 使用可能なすべてのドライブの名前が同じ場合は、それらのドライブをそれぞれのノードに同時に追加できます。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads adddrive create --cluster=CLUSTER_NAME --name REQUEST_NAME --drivesbyname all=DRIVE_NAME
----
** ドライブの名前が異なる場合は、各ノードにドライブを1つずつ追加できます（追加する必要があるドライブごとにこの手順を繰り返す必要があります）。大文字の情報を環境に適した値に置き換えます。
+
[source, kubectl]
----
kubectl astrads adddrive create --cluster=CLUSTER_NAME --name REQUEST_NAME --drivesbyname NODE_NAME=DRIVE_NAME
----




Astraデータストアがドライブの追加要求を作成し、要求の結果を含むメッセージが表示される。



== ドライブを交換します

クラスタ内のドライブで障害が発生した場合は、データの整合性を確保するために、できるだけ早くドライブを交換する必要があります。ドライブで障害が発生した場合は、クラスタのCRノードステータス、クラスタの健全性状態、および指標エンドポイントにある、障害が発生したドライブに関する情報を確認できます。障害が発生したドライブの情報を表示するには、次のコマンドを使用します。

.nodeStatus.driveStatuses で障害が発生したドライブを示すクラスタの例
[source, kubectl]
----
kubectl get adscl -A -o yaml
----
対応：

[listing]
----
...
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
...
nodeStatuses:
  - driveStatuses:
    - driveID: 31205e51-f592-59e3-b6ec-185fd25888fa
      driveName: scsi-36000c290ace209465271ed6b8589b494
      drivesStatus: Failed
    - driveID: 3b515b09-3e95-5d25-a583-bee531ff3f31
      driveName: scsi-36000c290ef2632627cb167a03b431a5f
      drivesStatus: Active
    - driveID: 0807fa06-35ce-5a46-9c25-f1669def8c8e
      driveName: scsi-36000c292c8fc037c9f7e97a49e3e2708
      drivesStatus: Active
...
----
障害が発生したドライブCRは、障害が発生したドライブのUUIDに対応する名前でクラスタ内に自動的に作成されます。

[source, kubectl]
----
kubectl get adsfd -A -o yaml
----
対応：

[listing]
----
...
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSFailedDrive
metadata:
    name: c290a-5000-4652c-9b494
    namespace: astrads-system
spec:
  executeReplace: false
  replaceWith: ""
 status:
   cluster: arda-6e4b4af
   failedDriveInfo:
     failureReason: AdminFailed
     inUse: false
     name: scsi-36000c290ace209465271ed6b8589b494
     path: /dev/disk/by-id/scsi-36000c290ace209465271ed6b8589b494
     present: true
     serial: 6000c290ace209465271ed6b8589b494
     node: sti-rx2540-300b.lab.org
   state: ReadyToReplace
----
[source, kubectl]
----
kubectl astrads faileddrive list --cluster arda-6e4b4af
----
対応：

[listing]
----
NAME       NODE                             CLUSTER        STATE                AGE
6000c290   sti-rx2540-300b.lab.netapp.com   ard-6e4b4af    ReadyToReplace       13m
----
.手順
. 交換可能なドライブを'kubectl strads faileddrive show -replacions'コマンドで一覧表示しますこのコマンドは'交換の制限に適合するドライブをフィルタリングします（クラスタでは未使用'マウントなし'パーティションなし'または障害が発生したドライブ以上）
+
可能な交換用ドライブをフィルタリングせずにすべてのドライブを一覧表示するには '--all' を 'show-replacements' コマンドに追加します

+
[source, kubectl]
----
kubectl astrads faileddrive show-replacements --cluster ard-6e4b4af --name 6000c290
----
+
対応：

+
[listing]
----
NAME  IDPATH             SERIAL  PARTITIONCOUNT   MOUNTED   SIZE
sdh   /scsi-36000c29417  45000c  0                false     100GB
----
. パスしたシリアル番号でドライブを交換するには 'replace' コマンドを使用しますコマンドは置換を完了するか '--wait' 時間が経過すると失敗します
+
[source, kubectl]
----
kubectl astrads faileddrive replace --cluster arda-6e4b4af --name 6000c290 --replaceWith 45000c --wait
----
+
対応：

+
[listing]
----
Drive replacement completed successfully
----
+

NOTE: kubectl の astrads faileddrive replace' が不適切なシリアル番号を使用して実行された場合 ' 次のようなエラーが表示されます

+
[source, kubectl]
----
kubectl astrads replacedrive replace --cluster astrads-cluster-f51b10a --name 6000c2927 --replaceWith BAD_SERIAL_NUMBER
Drive 6000c2927 replacement started
Failed drive 6000c2927 has been set to use BAD_SERIAL_NUMBER as a replacement
...
Drive replacement didn't complete within 25 seconds
Current status: {FailedDriveInfo:{InUse:false Present:true Name:scsi-36000c2 FiretapUUID:444a5468 Serial:6000c Path:/scsi-36000c FailureReason:AdminFailed Node:sti-b200-0214a.lab.netapp.com} Cluster:astrads-cluster-f51b10a State:ReadyToReplace Conditions:[{Message: "Replacement drive serial specified doesn't exist", Reason: "DriveSelectionFailed", Status: False, Type:' Done"]}
----
. ドライブ交換を再実行するには ' 前のコマンドで --force' を使用します
+
[source, kubectl]
----
kubectl astrads faileddrive replace --cluster astrads-cluster-f51b10a --name 6000c2927 --replaceWith VALID_SERIAL_NUMBER --force
----




== を参照してください。

* link:../use/kubectl-commands-ads.html["kubectlコマンドを使用してAstraデータストアのリソースを管理"]
* https://docs.netapp.com/us-en/astra-control-center/use/manage-backend.html#add-nodes-to-a-storage-backend-cluster["Astra Control Centerのストレージバックエンドクラスタにノードを追加します"^]

