---
sidebar: sidebar 
permalink: use/monitor-with-prometheus-grafana.html 
keywords: astra, astra data store, kubectl, endpoints, prometheus, grafana, visualization 
summary: Prometheus と Grafana を使用して、 Astra データストアのアセットを監視できます。 
---
= Prometheus と Grafana で指標を監視します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


PrometheusとGrafanaを使用して、Astraデータストアの指標を監視できます。PrometheusでAstra Data Store Kubernetesクラスタ指標エンドポイントから指標を収集するように設定でき、Grafanaを使用して指標データを表示できます。

.必要なもの
* PrometheusパッケージとGrafanaパッケージをAstra Data Storeクラスタ、またはAstra Data Storeクラスタと通信可能な別のクラスタでダウンロードしてインストールしておく必要があります。公式ドキュメントの指示に従って、各ツールをインストールします。
+
** https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_deploy_Prometheus_with_Astra_Data_Store["Prometheus をインストールする"^]
** https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_set_up_Grafana_for_monitoring_Astra_Data_Store_cluster["Grafana をインストールします"^]


* PrometheusとGrafanaがAstra Data Store Kubernetesクラスタと通信できる必要があります。PrometheusとGrafanaがAstra Data Storeクラスタにインストールされていない場合は、Astra Data Storeクラスタで実行されている指標サービスと通信できることを確認する必要があります。




== Prometheus を設定する

Astraデータストアは、KubernetesクラスタのTCPポート9341で指標サービスを公開します。このサービスから指標を収集するには、 Prometheus を設定する必要があります。

.手順
. Prometheus インストール用の「 prometheus.yml 」構成ファイルを編集します。
. Astra Data Storeサービス名とそのポートを指すサービスターゲットを追加します。例：
+
[listing]
----
scrape_configs:
static_configs:
- targets: ['astrads-metrics-service.astrads-system:9341']
----
. Prometheus サービスを開始します。




== Grafana を設定します

Prometheus で収集された指標を表示するように Grafana を設定できます。

.手順
. Grafana インストールの「 datasources.yaml 」設定ファイルを編集します。
. Prometheus をデータソースとして追加します。例：
+
[listing]
----
apiVersion: 1

datasources:
  - name: astradatastore-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      manageAlerts: false
----
. Grafana サービスを開始します。
. Grafana のマニュアルに記載されている手順に従ってください https://grafana.com/docs/grafana/latest/getting-started/getting-started/["始めましょう"^]。




== Grafana ダッシュボードテンプレートをインポートします

Astra Data Storeをインストールするためにダウンロードしたバンドルファイルには、Grafana内からインポートできるGrafanaダッシュボードテンプレートファイルが含まれています。このダッシュボードテンプレートを使用すると、Astraデータストアから取得できる指標の種類とその表示方法を確認できます。

.手順
. Astra Data Storeの.tar.gzバンドルを開きます。
. 'マニフェスト ' ディレクトリを開きます
. 「 graafana _cluster.json 」ファイルと「 graafana _volume.json 」ファイルを展開します。
. Grafana Web UI の使用、 https://grafana.com/docs/grafana/latest/dashboards/export-import/["でのダッシュボードテンプレートファイルを Grafana にインポートします"^]。

