---
sidebar: sidebar 
permalink: use/monitor-with-prometheus-grafana.html 
keywords: astra, astra data store, kubectl, endpoints, prometheus, grafana, visualization 
summary: Prometheus と Grafana を使用して、 Astra データストアのアセットを監視できます。 
---
= Prometheus と Grafana で指標を監視します
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


Prometheus と Grafana を使用して、 Astra データストアのプレビュー指標を監視できます。Prometheus で Astra Data Store プレビュー Kubernetes クラスタ指標エンドポイントから指標を収集するように設定でき、 Grafana を使用して指標データを表示できます。

.必要なもの
* Prometheus パッケージと Grafana パッケージを Astra Data Store プレビュークラスタ、または Astra Data Store プレビュークラスタと通信可能な別のクラスタでダウンロードしてインストールしておく必要があります。公式ドキュメントの指示に従って、各ツールをインストールします。
+
** https://prometheus.io/docs/prometheus/latest/installation/["Prometheus をインストールする"^]
** https://grafana.com/docs/grafana/latest/installation/debian/["Grafana をインストールします"^]


* Prometheus と Grafana が Astra データストアプレビュー Kubernetes クラスタと通信できる必要があります。Prometheus と Grafana が Astra Data Store プレビュークラスタにインストールされていない場合は、 Astra Data Store プレビュークラスタで実行されている指標サービスと通信できることを確認する必要があります。




== Prometheus を設定する

Astra Data Store プレビューでは、 Kubernetes クラスタの TCP ポート 9341 で指標サービスが公開されます。このサービスから指標を収集するには、 Prometheus を設定する必要があります。

.手順
. Prometheus インストール用の「 prometheus.yml 」構成ファイルを編集します。
. Astra Data Store プレビューサービス名とそのポートを指すサービス目標を追加します。例：
+
[listing]
----
scrape_configs:
static_configs:
- targets: ['astrads-metrics-service.astrads-system:9341']
----
. Prometheus サービスを開始します。




== Grafana を設定します

Prometheus で収集された指標を表示するように Grafana を設定できます。

.手順
. Grafana インストールの「 datasources.yaml 」設定ファイルを編集します。
. Prometheus をデータソースとして追加します。例：
+
[listing]
----
apiVersion: 1

datasources:
  - name: astradatastore-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      manageAlerts: false
----
. Grafana サービスを開始します。
. Grafana のマニュアルに記載されている手順に従ってください https://grafana.com/docs/grafana/latest/getting-started/getting-started/["始めましょう"^]。




== Grafana ダッシュボードテンプレートをインポートします

Astra Data Store Preview をインストールするためにダウンロードしたバンドルファイルには、 Grafana からインポートできる Grafana ダッシュボードテンプレートファイルが含まれています。このダッシュボードテンプレートを使用すると、 Astra データストアのプレビューで確認できる指標の種類とその表示方法を確認できます。

.手順
. Astra Data Store プレビューの tar.gz' バンドルを開きます
. 'マニフェスト ' ディレクトリを開きます
. 「 graafana _cluster.json 」ファイルと「 graafana _volume.json 」ファイルを展開します。
. Grafana Web UI の使用、 https://grafana.com/docs/grafana/latest/dashboards/export-import/["でのダッシュボードテンプレートファイルを Grafana にインポートします"^]。

