---
sidebar: sidebar 
permalink: use/uninstall-ads.html 
keywords: astra, astra data store, astra datastore, uninstall 
summary: Astra データストアをアンインストールするには、ワークロード、バインド、ボリューム、エクスポートポリシー、クラスタ、 ライセンス、導入環境、ネームスペース： 
---
= Astraデータストアを自動化されたスクリプトでアンインストールします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astraデータストアとコントロールプレーンをアンインストールするには、ワークロード、バインド、ボリューム、エクスポートポリシー、Astraデータストアクラスタ、ライセンス、導入環境、およびAstraデータストアネームスペースを削除します。

アンインストールにはさまざまな方法があります。

* <<Uninstall Astra Data Store with an automated script>>
* <<Uninstall Astra Data Store manually without a script>>
* <<Troubleshoot the Astra Data Store uninstall process>>




== Astraデータストアを自動化されたスクリプトでアンインストールします

このプロセスでは、自動スクリプトを使用してAstraデータストアをアンインストールします。

.必要なもの
* root 管理権限


Astra Data Storeのアンインストールプロセスでは、次の手順を実行できます。

* <<Remove existing workloads and bindings>>
* <<Uninstall Astra Data Store cluster>>
* <<Validate the removal of the astrads-system namespace>>
* <<Ensure containers are not running on worker nodes>>
* <<Delete OpenShift Container Platform resources>>




=== 既存のワークロードとバインドを削除します

Astraデータストアをアンインストールする前に、次のものを削除する必要があります

* Astraデータストアをストレージバックエンドとして使用するすべてのアプリケーションワークロード
* バックエンドとしてAstraデータストアを使用するTridentバインディング


これにより、 Kubernetes 環境をクリーンな状態のまま維持できます。これは、を再インストールする場合に重要です。



=== Astra データストアクラスタをアンインストールします

Astra Data Storeをアンインストールするには、ネットアップサポートサイトからダウンロードしたAstra Data Store tarファイルで「uninstall.sh」スクリプトを使用します。

. 'マニフェスト ' ディレクトリの 'uninstall.sh' を探します
. 次の「 sed 」コマンドを実行します。
+
[listing]
----
sed -i -e 's~netappsdsoperator.yaml~astradsoperator.yaml~' uninstall.sh
----
. 次のスクリプトを実行して、アンインストールする項目を指定します。
+
[listing]
----
./uninstall.sh

You must run this script with an argument specifying what should be uninstalled
To uninstall the ADS cluster run ./uninstall.sh cluster
To uninstall everything run ./uninstall all
----
. クラスタのみをアンインストールする場合は、「 uninstall.sh <cluster>` 」と入力します
+
それ以外の場合は、すべてをアンインストールするには、「 uninstall.sh 」と入力します

+

NOTE: ほとんどの場合、すべてをアンインストールします。その後クラスタを再導入する場合は、クラスタだけをアンインストールすることもできます。

. プロンプトで続行することを確認し、「 erasedata 」と入力します
+
対応：

+
[listing]
----
./uninstall.sh all

Enter 'erasedata' to confirm you want proceed with the uninstall: erasedata
+----------------------------------------------------+
| Wed Feb  2 10:14:01 EST 2022                       |
| ADS cluster uninstall started                      |
+----------------------------------------------------+
Deleting astradsvolumes
Deleted astradsvolumes
Deleting astradsexportpolicies
Deleted astradsexportpolicies
Deleting astradsvolumesnapshots
Deleted astradsvolumesnapshots
Deleting astradsclusters
Deleting astradsclusters
Deleting astradslicenses
Deleted astradslicenses

+----------------------------------------------------+
| Wed Feb  2 10:15:18 EST 2022                       |
| ADS cluster uninstall done                         |
+----------------------------------------------------+

+----------------------------------------------------+
| Wed Feb  2 10:15:18 EST 2022                       |
| ADS system uninstall started                       |
+----------------------------------------------------+
Removing astradsversion
astradsversion.astrads.netapp.io "astradsversion" deleted
Removed astradsversion
Removing daemonsets
daemonset.apps "astrads-ds-nodeinfo-astradsversion" deleted
Removed daemonsets
Removing deployments
deployment.apps "astrads-cluster-controller" deleted
deployment.apps "astrads-license-controller" deleted
deployment.apps "astrads-operator" deleted
Removed deployments
Removing all other AstraDS resources
namespace "astrads-system" deleted
customresourcedefinition.apiextensions.k8s.io "astradsautosupports.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradscloudsnapshots.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsclusters.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsexportpolicies.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsfaileddrives.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradslicenses.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsnfsoptions.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsnodeinfoes.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsnodemanagements.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsqospolicies.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsversions.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumefiles.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumes.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumesnapshots.astrads.netapp.io" deleted
role.rbac.authorization.k8s.io "astrads-astrads-system-admin-role" deleted
role.rbac.authorization.k8s.io "astrads-astrads-system-reader-role" deleted
role.rbac.authorization.k8s.io "astrads-astrads-system-writer-role" deleted
role.rbac.authorization.k8s.io "astrads-leader-election-role" deleted
role.rbac.authorization.k8s.io "astrads-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astrads-admin-clusterrole" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astrads-reader-clusterrole" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astrads-writer-clusterrole" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsautosupport-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsautosupport-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscloudsnapshot-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscloudsnapshot-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscluster-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscluster-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsexportpolicy-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsexportpolicy-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsfaileddrive-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsfaileddrive-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradslicense-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradslicense-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnfsoption-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnfsoption-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnodeinfo-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnodeinfo-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnodemanagement-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsnodemanagement-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsqospolicy-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsversion-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsversion-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolume-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolume-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolumefile-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolumefile-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolumesnapshot-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolumesnapshot-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-manager-role" deleted
rolebinding.rbac.authorization.k8s.io "astrads-astrads-admin-rolebinding" deleted
rolebinding.rbac.authorization.k8s.io "astrads-astrads-reader-rolebinding" deleted
rolebinding.rbac.authorization.k8s.io "astrads-astrads-writer-rolebinding" deleted
rolebinding.rbac.authorization.k8s.io "astrads-leader-election-rolebinding" deleted
rolebinding.rbac.authorization.k8s.io "astrads-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-astrads-admin-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-astrads-reader-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-astrads-writer-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-manager-rolebinding" deleted
configmap "astrads-autosupport-cm" deleted
configmap "astrads-firetap-cm" deleted
configmap "astrads-kevents-asup" deleted
configmap "astrads-metrics-cm" deleted
secret "astrads-autosupport-certs" deleted
+----------------------------------------------------+
| Wed Feb  2 10:16:36 EST 2022                       |
| ADS system uninstall done                          |
+----------------------------------------------------+
----




=== astrs-system 名前空間の削除を検証します

次のコマンドで結果が返されないことを確認します。

[listing]
----
kubectl get ns | grep astrads-system
----


=== ワーカーノードでコンテナが実行されていないことを確認します

'FIRETAAP' や 'netwd' などのコンテナがワーカー・ノードで実行されていないことを確認します各ノードで次のコマンドを実行します。

[listing]
----
ssh <mynode1>
# runc list
----


=== OpenShift Container Platform リソースを削除します

Red Hat OpenShift Container Platform（OCP）にAstraデータストアをインストールした場合は、OCPセキュリティコンテキスト制約（SCC）と役割バインディングリソースをアンインストールできます。

OpenShift では、セキュリティコンテキスト制約（ SCC ）を使用して、ポッドで実行できるアクションを制御します。

標準のアンインストールプロセスが完了したら、次の手順を実行します。

. SCC リソースを削除します。
+
[listing]
----
oc delete -f ads_privileged_scc.yaml
----
. ロールバインドリソースを削除します
+
[listing]
----
oc delete -f oc_role_bindings.yaml
----
+

NOTE: これらの手順で「 resources not found 」エラーを無視します。 





== スクリプトを使用せずにAstraデータストアを手動でアンインストールする

このプロセスでは、スクリプトを使用せずにAstraデータストアを手動でアンインストールします。

自動スクリプトを使用せずにAstraデータストアを手動でアンインストールするには、ワークロード、バインド、ボリューム、エクスポートポリシー、クラスタ、 ライセンス、導入環境、Astraデータストアネームスペース

.必要なもの
* root 管理権限


Astra Data Storeのアンインストールプロセスでは、次の手順を実行できます。

* <<Remove existing workloads and bindings>>
* <<Uninstall the Astra Data Store cluster and control plane>>
* <<Delete the license>>
* <<Delete the Astra Data Store installation>>
* <<Validate the removal of the astrads-system namespace>>
* <<Ensure containers are not running on worker nodes>>
* <<Delete OpenShift Container Platform resources>>




=== 既存のワークロードとバインドを削除します

Astraデータストアをアンインストールする前に、次のものを削除する必要があります

* Astraデータストアをストレージバックエンドとして使用するすべてのアプリケーションワークロード
* バックエンドとしてAstraデータストアを使用するTridentバインディング


これにより、 Kubernetes 環境をクリーンな状態のまま維持できます。これは、を再インストールする場合に重要です。



=== Astraデータストアクラスタとコントロールプレーンをアンインストールします

Astraデータストアを手動でアンインストールするには、次の手順に従います。



==== ボリュームとエクスポートポリシーを削除します

クラスタを削除する前に、Astraデータストアボリュームとエクスポートポリシーを削除する必要があります。


TIP: ボリュームとエクスポートポリシーを最初に削除しないと、Astra Data Storeボリュームオブジェクトが削除されるまで、クラスタの削除プロセスは一時停止します。クラスタの削除を開始する前に、それらの項目を削除する方が効率的です。

.手順
. ボリュームを削除します。
+
[listing]
----
~% kubectl delete astradsvolumes --all -A
~% kubectl get astradsvolumes -A
----
. エクスポートポリシーを削除します。
+
[listing]
----
~% kubectl delete astradsexportpolicies --all -A
~% kubectl get astradsexportpolicies -A

----




==== Astraデータストアクラスタを削除

クラスタを削除すると、Astra Data Storeクラスタオブジェクトのカスタムリソース（CR）とクラスタを対象としたリソースのみが削除される。


NOTE: オペレータ、 nodeinfo ポッド、およびクラスタコントローラ（ Kubernetes を対象としたリソース）は、クラスタを削除しても削除されません。

クラスタを削除すると ' 基盤となるオペレーティング・システムもノードからアンインストールされ 'FIRETAAP' および netwd' サービスが停止します

アンインストーラが完了するまでに約 1 分かかります。次に、Astraデータストアクラスタを対象としたリソースの削除が開始されます。

. クラスタを削除します。
+
[listing]
----
~% kubectl delete astradsclusters --all -A
~% kubectl get astradsclusters -A
----




=== ライセンスを削除します

. クラスタ内の各ワーカー・ノードに SSH 接続し ' ワーカー・ノードで 'FIRETAAP' または 'netwd' が実行されていないことを確認します
. Astraデータストアライセンスを削除します。
+
[listing]
----
~% kubectl delete astradslicenses --all -A
~% kubectl get astradslicenses -A

----




=== Astraデータストアのインストールを削除

クラスタ内のコントローラ、演算子、ネームスペース、およびサポートポッドを削除します。

. Astra Data Storeインストールオブジェクトを削除します。
+
[listing]
----
~% kubectl delete astradsversion astradsversion -n astrads-system
~% kubectl get astradsversion -n astrads-system

----
. データストアDemonSetsとすべてのAstraデータストアコントローラリソースを削除します。
+
[listing]
----
~% kubectl delete ds --all -n astrads-system
~% kubectl get ds -n astrads-system

~% kubectl delete deployments --all -n astrads-system
~% kubectl get deployments -n astrads-system
----
. 残りのアーティファクトと演算子 YAML ファイルを削除します。
+
[listing]
----
~% kubectl delete -f ./manifests/astradsoperator.yaml
~% kubectl get pods -n astrads-system

----




=== astrs-system 名前空間の削除を検証します

次のコマンドで結果が返されないことを確認します。

[listing]
----
~% kubectl get ns | grep astrads-system
----


=== ワーカーノードでコンテナが実行されていないことを確認します

'FIRETAAP' や 'netwd' などのコンテナがワーカー・ノードで実行されていないことを確認します各ノードで次のコマンドを実行します。

[listing]
----
ssh <mynode1>
# runc list
----


=== OpenShift Container Platform リソースを削除します

Red Hat OpenShift Container Platform（OCP）にAstraデータストアをインストールした場合は、OCPセキュリティコンテキスト制約（SCC）と役割バインディングリソースをアンインストールできます。

OpenShift では、セキュリティコンテキスト制約（ SCC ）を使用して、ポッドで実行できるアクションを制御します。

標準のアンインストールプロセスが完了したら、次の手順を実行します。

. SCC リソースを削除します。
+
[listing]
----
oc delete -f ads_privileged_scc.yaml
----
. ロールバインドリソースを削除します
+
[listing]
----
oc delete -f oc_role_bindings.yaml
----
+

NOTE: これらの手順で「 resources not found errors 」を無視します。 





=== 手動削除のサンプル

次に、手動アンインストールスクリプトの実行例を示します。

[listing]
----
$ kubectl delete astradsvolumes --all -A
No resources found
$ kubectl delete astradsexportpolicies --all -A
No resources found
$ kubectl delete astradsclusters --all -A
astradscluster.astrads.netapp.io "astrads-sti-c6220-09-10-11-12" deleted

$ kubectl delete astradslicenses --all -A
astradslicense.astrads.netapp.io "e900000005" deleted

$ kubectl delete astradsdeployment astradsdeployment -n astrads-system
astradsdeployment.astrads.netapp.io "astradsdeployment" deleted

$ kubectl delete ds --all -n astrads-system
daemonset.apps "astrads-ds-astrads-sti-c6220-09-10-11-12" deleted
daemonset.apps "astrads-ds-nodeinfo-astradsdeployment" deleted
daemonset.apps "astrads-ds-support" deleted

$ kubectl delete deployments --all -n astrads-system
deployment.apps "astrads-cluster-controller" deleted
deployment.apps "astrads-deployment-support" deleted
deployment.apps "astrads-license-controller" deleted
deployment.apps "astrads-operator" deleted

$ kubectl delete -f /.../firetap/sds/manifests/netappsdsoperator.yaml
namespace "astrads-system" deleted
customresourcedefinition.apiextensions.k8s.io "astradsautosupports.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradscloudsnapshots.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsclusters.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsdeployments.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsexportpolicies.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsfaileddrives.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradslicenses.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsnfsoptions.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsnodeinfoes.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsqospolicies.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumefiles.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumes.astrads.netapp.io" deleted
customresourcedefinition.apiextensions.k8s.io "astradsvolumesnapshots.astrads.netapp.io" deleted
role.rbac.authorization.k8s.io "astrads-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscloudsnapshot-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscloudsnapshot-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscluster-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradscluster-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradslicense-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradslicense-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolume-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-astradsvolume-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-autosupport-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-autosupport-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappexportpolicy-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappexportpolicy-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsdeployment-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsdeployment-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsnfsoption-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsnfsoption-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsnodeinfo-editor-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-netappsdsnodeinfo-viewer-role" deleted
clusterrole.rbac.authorization.k8s.io "astrads-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "astrads-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "astrads-proxy-rolebinding" deleted
configmap "astrads-autosupport-cm" deleted
configmap "astrads-firetap-cm" deleted
configmap "astrads-fluent-bit-cm" deleted
configmap "astrads-kevents-asup" deleted
configmap "astrads-metrics-cm" deleted
service "astrads-operator-metrics-service" deleted
 Error from server (NotFound): error when deleting "/.../export/firetap/sds/manifests/netappsdsoperator.yaml": deployments.apps "astrads-operator" not found

$ kubectl get ns | grep astrads-system

[root@sti-rx2540-535c ~]# runc list
ID      PID     STATUS    BUNDLE       CREATED    OWNER
----


== Astraデータストアのアンインストールプロセスのトラブルシューティング

アンインストールプロセスのトラブルシューティングが必要な場合は、次の点を確認してください。



=== ポッドが終了状態です

原因 ポッドがKubernetesで終了状態のままになる場合、Astraデータストアのアンインストールプロセスが必要になることがあります。

この問題 が発生した場合は、次のコマンドを実行して、 'astrs-system' 名前空間内のすべてのポッドを強制的に削除します。

[listing]
----
kubectl delete pods --all  -n astrads-system   --force --grace-period 0
----


=== QoSポリシーは古いクラスタをポイントしています

Astraデータストアクラスタのみを削除して再導入した場合、サービス品質（QoS）ポリシーが古いクラスタをポイントしていて検出できないために、永続的ボリューム要求（PVC）またはボリュームを作成できないことがあります。

. この問題を回避するには、Astraデータストアクラスタを削除したあとで、QoSポリシーを手動で削除します。
+
[listing]
----
kubectl delete AstraDSQosPolicy --all -A
----
. （クラスタだけでなく）Astraデータストア環境全体を削除する。
+
[listing]
----
uninstall.sh all
----




=== Astraデータストアを削除またはアンインストールしたあとに、キープロバイダCRSが削除されない

削除またはアンインストールするAstraデータストアクラスタ用に外部キープロバイダが設定されている場合は、削除されていないキープロバイダCRを手動でクリーンアップしなければならないことがあります。

.詳細
====
次の回避策 手順を使用します。

.手順
. キープロバイダCRSが削除されていないことを確認します。
+
[listing]
----
kubectl get astradskeyprovider --selector astrads.netapp.io/cluster=astrads-cluster-example -n astrads-system
----
+
対応：

+
[listing]
----
NAME                   AGE
externalkeyprovider1   94s
----
. キープロバイダCRSを削除します。
+
.. ファイナライザを取り外します。
+
[listing]
----
kubectl edit astradskeyprovider -n astrads-system
----
.. 以下のハイライトされたファイナライザラインを取り外します。
+
[listing]
----
kubectl edit astradskeyprovider externalkeyprovider1 -n astrads-system
----
+
[listing, subs="+quotes"]
----
apiVersion: astrads.netapp.io/v1beta1
kind: AstraDSKeyProvider
metadata:
  creationTimestamp: "2022-05-24T16:38:27Z"
  *finalizers:*
  *- astrads.netapp.io/astradskeyprovider-finalizer*
  generation: 1
  labels:
    astrads.netapp.io/cluster: astrads-cluster-example
    astrads.netapp.io/rsid: "1"
  name: externalkeyprovider1
  namespace: astrads-system
  resourceVersion: "1134699"
  uid: a11111b2-31c0-4575-b7f3-97f9abla1bla
spec:
  cluster: astrads-cluster-example
  kmipServer:
    hostnames:
    - 10.xxx.xxx.xxx
    port: 5696
    secretRef: externalkeyprovider1
status:
  keyProviderUUID: a1b2cd34-4fc6-5bae-9184-2288c673181d
  kmipServerStatus:
    capabilities: '{ KMIP_library_version()=17367809, KMIP_library_version_str()="KMIP
      1.9.3a  8-Apr-2019", KMIP_library_version_tag()="KMIP part of KMIP 1.9.3a  8-Apr-2019",
      KMIP_library_is_eval()=false, KMIP_library_fips_capable()=true(FIPS140), KMIP_SSL_provider_build_version()=268444095,
      KMIP_SSL_provider_version()=268444095, KMIP_SSL_provider_version_str()="OpenSSL
      1.0.2zb-fips  23 Sep 2021" }'
    keyServerUUID: 8422bdd0-74ad-579d-81bd-6d544ac4224a
----
.. ファイナライザを削除したら、キープロバイダCRを削除します。
+
[listing]
----
kubectl delete astradskeyprovider <key-provider-cr-name> -n astrads-system
----




====


=== Astra Control Center Web UIからAstraデータストアをアンインストールできない

Astraデータストアのアンインストールプロセスは、Astra Control Center Web UIから起動した場合に失敗することがあります。

この問題 が発生した場合は、次の手順を実行します。

.手順
. にログインします https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["ネットアップサポートサイト"^] Astra Data Storeバンドル(`Astra_Data-Store_22.05.tar')を'Astra Data Storeが存在するKubernetesクラスタにアクセスできるマシンにダウンロードします
. Astra Data Storeバンドルをダウンロードしたマシンにログインします。
. バンドルの内容を展開します。
+
[listing]
----
tar -xvf <path to tar file>/Astra_Data_Store_2022.05.tar
----
. アンインストールスクリプトが格納されているマニフェストディレクトリに変更します。
+
[listing]
----
cd astrads/manifests/
----
. Astraデータストアを手動で削除：
+
[listing]
----
./uninstall all
----

