---
sidebar: sidebar 
permalink: get-started/faq-ads.html 
keywords: faq, frequently asked questions, astra, astra data store, kubernetes, persistent volumes 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= Astra データストアのプレビューに関する FAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Astra Data Store のプレビュー版のインストール、設定、アップグレード、トラブルシューティングに関する FAQ を掲載しています。



== 一般的な質問

* 本番環境で Astra データストアプレビューを使用できますか？ * いいえAstra データストアはエンタープライズクラスの耐障害性を実現するように設計、開発されていますが、 Astra データストアプレビュー版は本番環境のワークロードには適していません。

* 仮想マシンのワークロードに対して Astra Data Store プレビューを使用できますか？ * Astra Data Store プレビューリリースは、ベアメタルマシンでも仮想マシンでも Kubernetes で実行されているアプリケーションに限定されます。今後のリリースでは、 Kubernetes と ESXi 仮想マシンの両方でアプリケーションがサポートされる予定です。を参照してください link:../get-started/requirements.html["Astra データストアの要件"]。

* Astra Data Store のプレビュー版には、他のネットアップ製品との依存関係はありますか？ *

はい。Astra Data Store のプレビューを利用するには、 NetApp CSI ドライバ Astra Trident バージョン 21.10.1 以降をワークロードの Kubernetes クラスタに導入する必要があります。詳細はこちら link:../get-started/requirements.html["Astra データストアの要件"]。

Astra Data Store プレビュー版クラスタをストレージバックエンドとして使用するアプリケーションであれば https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center の略"^] バージョン 21.12 データ保護、ディザスタリカバリ、 Kubernetes ワークロードの移行など、アプリケーション対応のデータ管理機能を活用するために必要です。

* Astra Data Store Preview Cluster の管理方法 * Astra Data Store のプレビュー資産の管理には、 kubectl コマンドと Kubernetes API 拡張機能を使用できます。

'kubectl astras コマンドには '-h' スイッチが含まれており ' 便利な使用法とフラグ・ドキュメントが提供されています

* アストラデータストアのプレビュークラスタ指標はどのように監視できますか？ * Cloud Insights を使用して、アストラデータストアのプレビュー指標を監視できます。を参照してください link:../use/monitor-with-cloud-insights.html["Cloud Insights で指標を監視"]。

ログを監視することもできます。を参照してください link:../use/configure-endpoints.html["イベントログを設定して監視する"]。

* Kubernetes クラスタで ONTAP や他のストレージプロバイダとともに Astra データストアプレビューを使用できますか？ * はい。Astra データストアプレビューは、アプリケーションクラスタ内の他のストレージプロバイダとともに使用できます。

* Astra Trident は、 Astra Data Store プレビューから Kubernetes クラスタを削除した場合にアンインストールされますか？ * Astra Trident は、 Astra Data Store プレビューをアンインストールしてもクラスタからアンインストールされません。Astra Trident のアンインストールが必要な場合は、別途アンインストールする必要があります。



== ライセンス

* Astra Data Store プレビューにはライセンスが必要ですか？ * はい、 Astra Data Store プレビューにはネットアップライセンスファイル（ NLF ）が必要です。

を参照してください link:../get-started/requirements.html["Astra データストアの要件"]。

* Astra データストアプレビューライセンスの有効期間はどのくらいですか？ * Astra データストアプレビューライセンスのデフォルト期間は、ダウンロード日から 90 日間です。



== Kubernetes クラスタに Astra データストアプレビューをインストールして使用

* ベアメタルまたは仮想マシンで実行されている Kubernetes クラスタに Astra Data Store プレビューをインストールできますか？ * はい。Astra データストアプレビューは、ベアメタルまたは ESXi VM で実行されている Kubernetes クラスタにインストールできます。を参照してください link:../get-started/requirements.html["Astra データストアのプレビュー要件"]。

* Astra Data Store プレビュー版でサポートされている Kubernetes のバージョンは何ですか。 *

Astra Data Store プレビューは、 v1.20 以降と互換性のある Kubernetes ディストリビューションで機能します。ただし、現時点では、 Kubernetes のすべてのディストリビューションで検証されているわけではありません。詳細はこちら link:../get-started/requirements.html["Astra データストアのプレビュー要件"]。

* My Kubernetes クラスタは 5 つ以上のワーカーノードで構成されています。Astra データストアプレビューを IT にインストールできますか。 * はい。Astra データストアプレビュークラスタは、 Kubernetes クラスタ内の 4 つのワーカーノードに導入できます。導入後、クラスタを 5 つのワーカーノードに拡張できます。

* Astra データストアプレビューは、プライベートレジストリからのオフラインインストールをサポートしていますか。 * はい。Astra データストアプレビューは、ローカルレジストリからオフラインでインストールできます。を参照してください link:../get-started/install-ads.html["Astra データストアプレビューをインストールします"]。ただし、 Astra データストアプレビューを継続的に利用するには、 NetApp AutoSupport バックエンド（ support.netapp.com ）に（直接またはプロキシ経由で）接続する必要があります。

* Astra データストアプレビューを使用するにはインターネットに接続する必要がありますか？ * Astra データストアプレビューを利用するには、必須の AutoSupport バンドルを定期的に送信するために、ネットアップ AutoSupport バックエンドに接続する必要があります。直接接続かプロキシ経由で接続できます。この接続がないか AutoSupport が無効な場合、クラスタがロックダウンされ、定期的なバンドルアップロードが再開されるまで新しいボリュームの作成が無効になります。

* Astra Data Store プレビューで使用する役割と権限は何ですか？ * Astra Data Store プレビューオペレータを配備するには、 kubeadmin である必要があります。

Astra Data Store のプレビューには、ノードの選択に使用されるノードリソースを検出するための「 astra -ds-nodeinfo -astradsversion 」という特権的なデミスがあります。

さらに、管理者は、権限付き Kubernetes ジョブを使用して、選択したワーカーノードにストレージクラスタのコンテナをインストールし、 Astra Data Store プレビューストレージクラスタを構築します。

* Astra Data Store プレビューインストール用に更新する必要があるマニフェストファイルは何ですか？ * からダウンロードした Astra Data Store プレビューバンドルから https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["ネットアップサポートサイト"^]では、次のマニフェストが表示されます。

* Astradscluster.yaml
* Astradsoperator.yaml
* astadsversion.yaml
* Monitoring_operator.yaml


配備固有の設定で 'astraadscluster.yaml マニフェストを更新する必要がありますを参照してください link:../get-started/install-ads.html["Astra データストアプレビューをインストールします"]。



== トラブルシューティングとサポート

ネットアップのコンテナ向け Slack チャネルを使用して、ネットアップの Astra データストアプレビューでコミュニティサポートにアクセスできます。このチャネルの監視は、ネットアップのサポートエンジニアとテクニカルマーケティングエンジニアが行います。

https://netapp.io/slack["ネットアップコンテナ向け Slack チャンネル"^]

プレビューリリースでは、システムがクラウドに接続され、 NetApp Active IQ ツールと AutoSupport ツールに統合されている必要があります。

を参照してください link:../support/get-help-ads.html["Astra データストアサポート業務"]。

* サポートケースを作成する方法、または簡単な質問を明確にする方法を教えてください。 * サポートケースを作成する方法、または簡単な質問について説明する方法については、問題またはの質問を参照してください https://netapp.io/slack["ネットアップコンテナ向け Slack チャンネル"^]。ネットアップサポートがご連絡し、ベストエフォートベースでサポートを提供します。

* 新機能のリクエストをどのようにして提出しますか？ * サポートされている構成や機能について質問がある場合は、 astra.feedback@netapp.com までお問い合わせください。

* サポートログバンドルの生成方法については、を参照してください link:../support/get-help-ads.html#generate-support-bundle-to-provide-to-netapp-support["サポートバンドルの生成"] Astra Data Store プレビュー版のサポートログバンドルをセットアップおよびダウンロードする手順については、こちらを参照してください。

* Astra データストアプレビューで Kubernetes ノードが見つかりません。どうすれば修正できますか？ * を参照してください link:../get-started/install-ads.html["Astra データストアプレビューをインストールします"]。

* IPv6 アドレスは管理ネットワーク、データネットワーク、クラスタネットワークに使用できますか？ * いいえ、 Astra データストアプレビューでサポートされているのは IPv4 アドレスのみです。IPv6 のサポートは、 Astra データストアプレビューの今後のリリースで追加される予定です。

* Astra Data Store プレビューでボリュームをプロビジョニングする際に使用される NFS のバージョンは何ですか？ * デフォルトでは、 Kubernetes アプリケーション用にプロビジョニングされたすべてのボリュームに対して、 Astra Data Store プレビューで NFS v4.1 がサポートされています。

* 大容量ドライブで Astra データストアプレビューを構成しても、大容量の永続ボリュームを取得できないのはなぜですか？ * Astra データストアプレビューにより、 Astra データセンターのすべてのノードでプロビジョニングされる最大容量が 1TiB に、すべてのノードで最大 5TiB に制限されます クラスタのプレビューを保存します。

を参照してください link:../get-started/requirements.html["Astra データストアのプレビュー要件"] および link:capabilities.html["Astra データストアのプレビュー制限"]。



== Astra データストアプレビューのアップグレード

* Astra Data Store プレビューリリースからアップグレードできますか。 * いいえAstra データストアプレビューは本番環境のワークロードには適用されず、 Astra データストアプレビューソフトウェアの新しいリリースには新規インストールが必要になります。
