---
sidebar: sidebar 
permalink: get-started/faq-ads.html 
keywords: faq, frequently asked questions, astra, astra data store, kubernetes, persistent volumes 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= Astraデータストアに関するFAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Astra Data Store Early Access Programリリースのインストール、設定、アップグレード、およびトラブルシューティングに関するFAQを掲載しています。



== 一般的な質問

*製造にはAstra Data Store Early Access Programリリースを使用できますか。*いいえAstraデータストアは、エンタープライズクラスの耐障害性を実現するように設計、開発されていますが、AstraデータストアのEarly Access Programリリースは本番環境のワークロードをターゲットとしたものではありません。

*仮想マシンのワークロードにAstraデータストアを使用できますか。*はい。Astraデータストアは、KubernetesとVMwareのVVOLワークロードの両方をサポートします。

を参照してください link:../use-vmware/use-ads-vmware-overview.html["VMwareを使用したAstraデータストアの詳細をご確認ください"]。

* VMware vSphereを使用してAstraデータストアを管理できますか？*はい、ネットアップのAstraプラグインを使用して、ネットアップのAstraデータストアをvCenterでネイティブに管理できます。を参照してください link:../use-vmware/manage-ads-vmware.html["VMware環境のAstra Data Storeコンポーネントを管理します"]。

* Astraデータストアには、他のネットアップ製品との依存関係はありますか？*

はい。Astra Data Storeでは、NetApp CSIドライバAstra Tridentバージョン21.10.1以降をワークロードのKubernetesクラスタに導入する必要があります。詳細はこちら link:../get-started/requirements.html["Astra データストアの要件"]。

VMwareワークフローとNetApp Astra Plugin for VMware vSphereを有効にするには、Astra Control Centerが必要です。

Astraデータストアクラスタをストレージバックエンドとして使用するアプリケーションは、を使用できます https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center の略"^] データ保護、ディザスタリカバリ、Kubernetesワークロードの移行など、アプリケーション対応のデータ管理機能を活用するため。

* Astra Data Storeクラスタの管理方法* kubectlコマンドを使用し、Kubernetes API拡張機能を使用してAstraデータストアのリソースを管理できます。

'kubectl astras コマンドには '-h' スイッチが含まれており ' 便利な使用法とフラグ・ドキュメントが提供されています

* Astraデータストアクラスタの指標を監視するにはどうすればよいですか？* Cloud Insights を使用して、Astraデータストアの指標を監視できます（を参照） link:../use/monitor-with-cloud-insights.html["Cloud Insights で指標を監視"]）またはKubernetesのネイティブ監視（を参照 link:../use/monitor-with-prometheus-grafana.html["PrometheusとGrafanaで監視します"]）。

ログを監視することもできます。を参照してください link:../use/configure-endpoints.html["イベントログを設定して監視する"]。

* KubernetesクラスタでONTAP やその他のストレージプロバイダとともにAstraデータストアを使用できますか？*はい。Astraデータストアは、アプリケーションクラスタ内の他のストレージプロバイダとともに使用できます。

* Astra Tridentは、AstraデータストアからKubernetesクラスタを削除してもアンインストールされますか？* Astra Tridentは、Astraデータストアをアンインストールしてもクラスタからアンインストールされません。Astra Trident のアンインストールが必要な場合は、別途アンインストールする必要があります。



== ライセンス

* Astraデータストアにはライセンスが必要ですか？*はい、Astraデータストアには、Early Access Program（EAP；早期アクセスプログラム）用の評価用ネットアップライセンスファイル（NLF）が必要です。

を参照してください link:../get-started/requirements.html["Astra データストアの要件"]。

* Astraデータストア評価ライセンスの有効期間はどのくらいですか？* Astraデータストアライセンスのデフォルト期間は、ダウンロード日から90日間です。



== KubernetesクラスタへのAstraデータストアのインストールと使用

*ベアメタルまたは仮想マシンで稼働するKubernetesクラスタにAstraデータストアをインストールできますか？*はい。Astraデータストアは、ベアメタルまたはvSphere VMで実行されているKubernetesクラスタにインストールできます。を参照してください link:../get-started/requirements.html["Astra データストアの要件"]。

* Astra Data StoreでサポートされているKubernetesのバージョンは何ですか。*

Astraデータストアは、v1.20以降と互換性のあるKubernetesディストリビューションで動作します。ただし、現時点では、 Kubernetes のすべてのディストリビューションで検証されているわけではありません。詳細はこちら link:../get-started/requirements.html["Astra データストアの要件"]。

* My Kubernetesクラスタは4つ以上のワーカーノードで構成されています。AstraデータストアをITにインストールできますか。*はい。Astraデータストアクラスタは、最初にKubernetesクラスタ内の4つのワーカーノードに導入する必要があります。導入後、クラスタを最大16個のワーカーノードまで拡張できます。

* Astraデータストアはプライベートレジストリからのオフラインインストールをサポートしていますか。*はい。Astraデータストアは、ローカルレジストリからオフラインでインストールできます。を参照してください link:../get-started/install-ads.html["Astra データストアをインストール"]。

*アストラデータストアを使用するにはインターネット接続が必要ですか？*いいえ、アストラデータストア早期アクセスプログラムではインターネット接続は必要ありません。ただし、テレメトリバンドルを定期的に送信するために、NetApp AutoSupport バックエンドに接続することを推奨します。直接接続かプロキシ経由で接続できます。

* Astra Data Storeで使用する役割と権限は何ですか。* Astra Data Storeオペレータを配備するには、kubeadminである必要があります。

Astra Data Storeには、ノードの選択に使用されるノードリソースを検出するための「astrs-ds-nodeinfo」という特権的なデーモンがあります。

さらに、管理者は、権限付きKubernetesジョブを使用して、選択したワーカーノードにストレージクラスタのコンテナをインストールし、Astra Data Storeストレージクラスタを構築します。

* Astra Data Storeインストール用に更新する必要があるマニフェストファイルを教えてください。*からダウンロードしたAstra Data Storeバンドルから https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["ネットアップサポートサイト"^]では、次のマニフェストが表示されます。

* Astradscluster.yaml
* Astradsoperator.yaml
* astadsversion.yaml
* Monitoring_operator.yaml


配備固有の設定で 'astraadscluster.yaml マニフェストを更新する必要がありますを参照してください link:../get-started/install-ads.html["Astra データストアをインストール"]。



== トラブルシューティングとサポート

ネットアップのコンテナ向けSlackチャネルを使用して、ネットアップのAstraデータストアからコミュニティサポートにアクセスできます。このチャネルの監視は、ネットアップのサポートエンジニアとテクニカルマーケティングエンジニアが行います。

https://netapp.io/slack["ネットアップコンテナ向け Slack チャンネル"^]

を参照してください link:../support/get-help-ads.html["Astra データストアサポート業務"]。

* サポートケースを作成する方法、または簡単な質問を明確にする方法を教えてください。 * サポートケースを作成する方法、または簡単な質問について説明する方法については、問題またはの質問を参照してください https://netapp.io/slack["ネットアップコンテナ向け Slack チャンネル"^]。ネットアップサポートがご連絡し、ベストエフォートベースでサポートを提供します。

* 新機能のリクエストをどのようにして提出しますか？ * サポートされている構成や機能について質問がある場合は、 astra.feedback@netapp.com までお問い合わせください。

* サポートログバンドルの生成方法については、を参照してください link:../support/get-help-ads.html#generate-support-bundle-to-provide-to-netapp-support["サポートバンドルの生成"] Astraデータストア用のサポートログバンドルのセットアップとダウンロードの手順については、を参照してください。

* AstraデータストアがKubernetesノードを見つけられない。どうすれば修正できますか？ * を参照してください link:../get-started/install-ads.html["Astra データストアをインストール"]。

* IPv6アドレスを管理、データ、およびクラスタネットワークに使用できますか？*いいえ、AstraデータストアはIPv4アドレスのみをサポートしています。IPv6のサポートは、Astraデータストアの今後のリリースで追加される予定です。

* Astra Data Storeでボリュームをプロビジョニングする際に使用されるNFSのバージョンは何ですか？* Astra Data Storeでは、Kubernetesアプリケーション用にプロビジョニングされたすべてのボリュームにNFS v4.1、VMwareワークロード用にプロビジョニングされたすべてのボリュームにNFSv3バージョン4.1がサポートされています。

を参照してください link:../get-started/requirements.html["Astra データストアの要件"] および link:capabilities.html["Astraデータストアの制限"]。



== Astraデータストアのアップグレード

* Astra Data Storeプレビューリリースからアップグレードできますか*はい。Astra Data Store Early Access Programリリースから将来のリリースにアップグレードできます。
