---
sidebar: sidebar 
permalink: get-started/install-ads.html 
keywords: astra data store, install, deploy, openshift, astra control center, rancher, anthos 
summary: Kubernetesネイティブコマンドを使用するか、Astra Control CenterのUIを使用して、Astraデータストアをインストールできます。 
---
= Astra データストアをインストール
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Kubernetesネイティブコマンドを使用するか、Astra Control CenterのUIを使用して、Astraデータストアをインストールできます。



== インストールオプション

* * Kubernetesネイティブコマンド*：Kubernetesネイティブコマンドを使用してAstraデータストアをインストールするには、で説明するインストール手順を実行します <<Install Astra Data Store,この手順>>。
* * Astra Control Centerを使用している場合*：Astra Control Centerを使用してAstraデータストアをインストールするには、に記載されているインストール手順を実行します <<Install Astra Data Store using Astra Control Center,この手順>>。




== 必要なもの

* link:requirements.html["インストールを開始する前に、Astra Data Store環境を準備します"]。
* にアクセスします https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["ネットアップサポートサイト"^]。 https://www.netapp.com/cloud-services/astra/data-store-form/["登録"^] フルアクセスのネットアップサポートサイトアカウントがない場合は、評価版をダウンロードしてください。
* A link:../get-started/requirements.html#licensing["ネットアップライセンスファイル（ NLF ）"] Astraデータストア向け。ライセンスのダウンロード手順がお客様に送信されます https://www.netapp.com/cloud-services/astra/data-store-form["サインアップ"^]。
* アクティブなコンテキストのクラスタ管理者権限があるアクティブな kubeconfig です。
* の理解 link:../get-started/faq-ads.html#installation-and-use-of-astra-data-store-on-a-kubernetes-cluster["ロールと権限"] Astraデータストアで使用。




== Astra データストアをインストール

標準のKubernetesクラスタを使用するAstraデータストアのインストールプロセスでは、以下の手順を大まかに実行できます。また、Red Hat OpenShift Container Platform（OCP）環境用の追加のインストール手順についても説明します。

* <<Download the Astra Data Store bundle and extract the images>>
* <<Copy the binary and push images to your local registry>>
* <<OpenShift procedure>>
* <<Install the Astra Data Store operator>>
* <<Deploy the Astra Data Store version YAML>>
* <<Apply the Astra Data Store license>>
* <<Install the Astra Data Store cluster>>
* <<Understand deployment-related events>>



NOTE: Google AnthosでAstraデータストアを使用するには、以下のインストール手順を実行し、AstraデータストアクラスタをAnthos環境に追加します。


NOTE: Rancher RKE環境でAstra Data Storeをインストールするには、次のインストール手順を実行し、kubectlコマンドのrancherコマンドを置き換えます。



=== Astra Data Storeバンドルをダウンロードしてイメージを展開

. にログインします https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["ネットアップサポートサイト"^] Astra Data Storeバンドルをダウンロードします(`Astra_Data-Store_22.05.tar')
+

NOTE: 以前のバージョンのバンドルに関する手順については、を参照してください link:../acc-earlier-versions.html["該当するバージョンのドキュメント"]。

. （任意）次のコマンドを使用して、バンドルのシグニチャを確認します。
+
[listing]
----
openssl dgst -sha256 -verify Astra_Data_Store_2022.05.pub -signature Astra_Data_Store_2022.05.sig 2022.12.01_ads.tar
----
. ディレクトリを作成します。
+
[listing]
----
mkdir Astra_Data_Store_2022.05
cd Astra_Data_Store_2022.05
----
. 画像を抽出します。
+
[listing]
----
tar -xvf <path to tar file>/Astra_Data_Store_2022.05.tar
----
+

NOTE: 画像は、作業ディレクトリ内に作成された「astrs/images」ディレクトリに抽出されます。





=== バイナリをコピーし、ローカルレジストリにイメージをプッシュします

. k8s kubectlバイナリがインストールされている標準パスに'イメージを抽出するために使用したディレクトリからkubectl-astrasバイナリをコピーします(以下の例では'/usr/bin/がパスとして使用されます)kubectl-astrasは、Astraデータストアクラスタをインストールおよび管理するカスタムのkubectl拡張機能です。
+

TIP: kubectlバイナリがインストールされているパスを検索するには'which kubectl'コマンドを使用します

+
[listing]
----
cp -p ./astrads/bin/kubectl-astrads /usr/bin/.
----
. Astra Data Storeイメージディレクトリ内のファイルをローカルレジストリに追加します。
+

NOTE: 以下の画像の自動ロードについては、サンプルスクリプトを参照してください。

+
.. レジストリにログインします。
+
[listing]
----
docker login [your_registry_path]
----
.. 環境変数を、Astraデータストアイメージをプッシュするレジストリパス（例：repo.company.com`）に設定します。
+
[listing]
----
export REGISTRY=repo.company.com/astrads
----
.. スクリプトを実行して Docker にイメージをロードし、イメージにタグを付けます。 [[[</Z1>[</Z1>[</Z1>_image_local_registry_push]] ローカルレジストリにイメージをプッシュします。 </Z2>
+
[listing]
----
for astraImageFile in $(ls astrads/images/*.tar) ; do
   astraImage=$(docker load --input ${astraImageFile} | sed 's~Loaded image: ~~')
   astraImageShort=`echo $astraImage | sed 's~.*/~~'`
   docker tag ${astraImage} ${REGISTRY}/${astraImageShort}
   docker push ${REGISTRY}/${astraImageShort}
done
sed -i 's~\[YOUR REGISTRY\]~'${REGISTRY}'~' ./astrads/manifests/*.yaml
----






=== OpenShift 手順 の略

以下の手順 は、Red Hat OpenShift Container Platform（OCP）への導入にのみ使用してください。OCP以外のKubernetesクラスタへの導入については、この手順 をスキップしてください。

.詳細
====
すべてのAstraデータストアコンポーネントをインストールする名前空間「astrs-system」を作成します。

以下の手順は、 Red Hat OpenShift Container Platform （ OCP ）に導入する場合にのみ必要です。

. ネームスペースを作成します。
+
[listing]
----
kubectl create -f ads_namespace.yaml
----
+
例： ads_namespac.yaml

+
[listing]
----
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: operator
  name: astrads-system
----


OpenShift では、セキュリティコンテキスト制約（ SCC ）を使用して、ポッドで実行できるアクションを制御します。デフォルトでは、任意のコンテナの実行には制限付き SCC が付与され、その SCC で定義された機能のみが付与されます。

制限付きSCCでは、Astra Data Storeクラスタポッドで必要な権限は提供されません。この手順 を使用して、Astraデータストアに対して必要な権限（サンプルに記載）を付与します。

カスタムSCCをAstra Data Storeネームスペースのデフォルトのサービスアカウントに割り当てます。

以下の手順は、 Red Hat OpenShift Container Platform （ OCP ）に導入する場合にのみ必要です。

. カスタム SCC を作成します。
+
[listing]
----
kubectl create -f ads_privileged_scc.yaml
----
+
サンプル： ads_privileged_ssc.yaml

+
[listing]
----
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'ADS privileged. Grant with caution.'
    release.openshift.io/create-only: "true"
  name: ads-privileged
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:astrads-system:default
volumes:
- '*'
----
. 「 OC get SCC 」コマンドを使用して、新たに追加された SCC を表示します。
+
[listing]
----
# oc get scc/ads-privileged
NAME             PRIV   CAPS    SELINUX    RUNASUSER   FSGROUP    SUPGROUP   PRIORITY     READONLYROOTFS   VOLUMES
ads-privileged   true   ["*"]   RunAsAny   RunAsAny    RunAsAny   RunAsAny   <no value>   false            ["*"]
#
----


Astraデータストアのデフォルトのサービスアカウントで使用する、必要なロールとロールのバインドを作成します。

次のYAML定義では'Astraデータストアのリソースがastrads.netapp.io` APIグループに必要とするさまざまな役割を割り当てます(役割のバインドを使用)

以下の手順は、 Red Hat OpenShift Container Platform （ OCP ）に導入する場合にのみ必要です。

. 定義されたロールとロールのバインドを作成します。
+
[listing]
----
kubectl create -f oc_role_bindings.yaml
----
+
例： OC_ROLE_bindings. yaml

+
[listing]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privcrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ads-privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-scc-rolebinding
  namespace: astrads-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privcrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: astrads-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ownerref
  namespace: astrads-system
rules:
- apiGroups:
  - astrads.netapp.io
  resources:
  - '*/finalizers'
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: or-rb
  namespace: astrads-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ownerref
subjects:
- kind: ServiceAccount
  name: default
  namespace: astrads-system
----


====


=== プライベートイメージレジストリを設定します

特定の環境では、オプションとして設定を変更して、シークレットを使用するプライベートレジストリからイメージをプルできます。

. 前の手順に進んでいない限り'astrs-system'名前空間を作成します
+
[listing]
----
kubectl create namespace astrads-system
----
. シークレットを作成します。
+
[listing]
----
kubectl create secret docker-registry <secret-name> -n astrads-system --docker-server=<registry name> --docker-username= <registry username> --docker-password=<registry user password>
----
. サービスアカウントにシークレット設定情報を追加します。
+
[listing]
----
kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "<secret-name>"}]}' -n astrads-system
----
+

NOTE: これらの変更は、のときに適用されます <<Install the Astra Data Store operator,Astra Data Storeオペレータをインストール>>。





=== Astra Data Storeオペレータをインストール

. Astraデータストアマニフェストの一覧を表示します。
+
[listing]
----
ls astrads/manifests/*yaml
----
+
対応：

+
[listing]
----
astrads/manifests/monitoring_operator.yaml
astrads/manifests/astradscluster.yaml
astrads/manifests/astradsversion.yaml
astrads/manifests/astradsoperator.yaml
astrads/manifests/vasa_asup_certs.yaml
astrads/manifests/manifest.yaml
astrads/manifests/configuration.yaml
----
. kubectl apply を使用してオペレータを配備します。
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradsoperator.yaml
----
+
対応：

+

NOTE: ネームスペースの応答は、標準インストールとのどちらを実行したかによって異なる場合があります link:../get-started/install-ads.html#openshift-procedure["OCPのインストール"]。

+
[listing]
----
namespace/astrads-system created
customresourcedefinition.apiextensions.k8s.io/astradsadddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsautosupports.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradscloudsnapshots.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsclusters.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsexportpolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsfaileddrives.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradskeyproviders.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradslicenses.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnfsoptions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodeinfoes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsnodemanagements.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsqospolicies.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradssearkeyrotaterequests.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsversions.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumefiles.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumes.astrads.netapp.io created
customresourcedefinition.apiextensions.k8s.io/astradsvolumesnapshots.astrads.netapp.io created
role.rbac.authorization.k8s.io/astrads-astrads-system-admin-role created
role.rbac.authorization.k8s.io/astrads-astrads-system-reader-role created
role.rbac.authorization.k8s.io/astrads-astrads-system-writer-role created
role.rbac.authorization.k8s.io/astrads-leader-election-role created
role.rbac.authorization.k8s.io/astrads-manager-role created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-admin-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-reader-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astrads-writer-clusterrole created
clusterrole.rbac.authorization.k8s.io/astrads-astradsautosupport-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsautosupport-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscloudsnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradscluster-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsexportpolicy-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsexportpolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsfaileddrive-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsfaileddrive-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradslicense-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnfsoption-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnfsoption-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodeinfo-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodeinfo-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodemanagement-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsnodemanagement-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsqospolicy-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsversion-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsversion-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolume-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumefile-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumefile-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumesnapshot-editor-role created
clusterrole.rbac.authorization.k8s.io/astrads-astradsvolumesnapshot-viewer-role created
clusterrole.rbac.authorization.k8s.io/astrads-manager-role created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-admin-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-reader-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-astrads-writer-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-admin-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-reader-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-astrads-writer-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/astrads-manager-rolebinding created
configmap/astrads-autosupport-cm created
configmap/astrads-firetap-cm created
configmap/astrads-kevents-asup created
configmap/astrads-metrics-cm created
secret/astrads-autosupport-certs created
secret/astrads-webhook-server-cert created
service/astrads-webhook-service created
deployment.apps/astrads-operator created
----
. Astra データストアオペレータポッドが起動し、実行中であることを確認します。
+
[listing]
----
kubectl get pods -n astrads-system
----
+
対応：

+
[listing]
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-operator-5ffb94fbf-7ln4h    1/1     Running   0          17m
----




=== Astra Data StoreバージョンYAMLを導入します

. kubectl apply を使用した導入：
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradsversion.yaml
----
. ポッドが実行されていることを確認します。
+
[listing]
----
kubectl get pods -n astrads-system
----
+
対応：

+
[listing]
----
NAME                                          READY   STATUS    RESTARTS   AGE
astrads-cluster-controller-7f6f884645-xxf2n   1/1     Running   0          117s
astrads-ds-nodeinfo-2jqnk                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-dbk7v                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-rn9tt                     1/1     Running   0          2m7s
astrads-ds-nodeinfo-vsmhv                     1/1     Running   0          2m7s
astrads-license-controller-fb8fd56bc-bxq7j    1/1     Running   0          2m2s
astrads-operator-5ffb94fbf-7ln4h              1/1     Running   0          2m10s
----




=== Astraデータストアライセンスを適用します

. ネットアップから入手したネットアップライセンスファイル（NLF）を適用します。コマンドを実行する前に、使用しているクラスタの名前（「 <AstrA-Data-Store-cluster-name>` ）を入力します <<Install the Astra Data Store cluster,導入に進みます>> または ' すでに配備されているか ' ライセンス・ファイルへのパス (`<file_path/file.txt>`) があります
+
[listing]
----
kubectl astrads license add --license-file-path <file_path/file.txt> --ads-cluster-name <Astra-Data-Store-cluster-name> -n astrads-system
----
. ライセンスが追加されたことを確認します。
+
[listing]
----
kubectl astrads license list
----
+
対応：

+
[listing]
----
NAME                     ADSCLUSTER                 VALID   PRODUCT             EVALUATION  ENDDATE     VALIDATED
e100000006-ads-capacity  astrads-example-cluster    true    Astra Data Store    true        2023-01-23  2022-04-04T14:38:54Z
----




=== Astraデータストアクラスタをインストール

. YAML ファイルを開きます。
+
[listing]
----
vim ./astrads/manifests/astradscluster.yaml
----
. YAML ファイルで次の値を編集します。
+

NOTE: YAML ファイルの簡単な例は、次の手順を実行します。

+
.. （必須） * Metadata* ：「 metadata 」で、「 name 」の文字列をクラスタの名前に変更します。このクラスタ名は、ときと同じである必要があります <<Apply the Astra Data Store license,ライセンスを適用します>>。
.. ( 必須 )*Spec*:'spec' の次の必須値を変更します
+
*** ライセンスとAstra Data Storeのインストール・サイズに応じて'adsNodeConfig'の値をインストールに必要な値に変更します
+
**** 小：CPU 9個とメモリ38個
**** 中：CPU 23基、メモリ94基


*** (オプション)「adsNodeSelector`」セクションに関するコメントを削除します。選択したワーカーノードのプールにのみインストールするようにAstraデータストアを制限する場合は、この設定を行います。
*** （オプション）Astra Data Storeクラスタで使用するノードの数を4-16の範囲で指定します。
*** 「 mvip 」文字列を、クラスタ内の任意のワーカーノードからルーティング可能なフローティング管理 IP の IP アドレスに変更します。
*** 「 adsDataNetworks 」に、 NetApp ボリュームをマウントするホストからルーティング可能なフローティング IP アドレス（「アドレス」）をカンマで区切って追加します。ノードごとに 1 つのフローティング IP アドレスを使用します。データネットワークIPアドレスは、Astraデータストアノードと同じ数以上にする必要があります。Astraデータストアの場合、この方法は、あとでクラスタを拡張する場合は少なくとも4つのアドレス、または最大16個を意味します。
*** 「 adsDataNetworks 」で、データネットワークが使用するネットマスクを指定します。
*** 「 adsNetworkInterfaces 」で、「 <mgmt_interface_name> 」および「 <cluster_and _storage_interface_name> 」の値を、管理、クラスタ、およびストレージに使用するネットワークインターフェイス名に置き換えます。名前を指定しない場合、ノードのプライマリインターフェイスが管理、クラスタ、ストレージのネットワークに使用されます。「adsNetworkInterfaces」セクションのコメントも削除してください。
+

NOTE: クラスタとストレージのネットワークのインターフェイスが同じである必要があります。Astraデータストア管理インターフェイスは、Kubernetesノードの管理インターフェイスと同じである必要があります。



.. （任意） * monitoringConfig* ：を設定する場合 <<Install the monitoring operator,監視オペレータ>> （監視に Astra Control Center を使用していない場合はオプション）、セクションからコメントを削除し、エージェント CR （監視用オペレータリソース）が適用されるネームスペース（デフォルトは「 NetApp-monitoring 」）を追加し、前の手順で使用したレジストリ（「 Your_registry_path 」）のリポジトリパスを追加します。
.. （任意） * autoSupportConfig * ：を保持します link:../support/autosupport.html["AutoSupport"] プロキシを設定する必要がない場合のデフォルト値は次のとおりです。
+
*** 「 ProxyURL 」の場合は、 AutoSupport バンドルの転送に使用するポートにプロキシの URL を設定します。


+

NOTE: 簡潔にするために、以下のYAMLサンプルからコメントが削除されています。



+
[listing, subs="+quotes"]
----
apiVersion: astrads.netapp.io/v1beta1
kind: AstraDSCluster
*metadata:*
  *name: astrads-cluster-name*
  namespace: astrads-system
*spec:*
  *adsNodeConfig:*
    *cpu: 9*
    *memory: 38*
  # [Optional] Specify node selector labels to select the nodes for creating ADS cluster
  # adsNodeSelector:
  #   matchLabels:
  #     customLabelKey: customLabelValue
  adsNodeCount: 4
  *mvip: ""*
  *adsDataNetworks:*
    *- addresses: ""*
      *netmask:*
  # Specify the network interface names to use for management, cluster and storage networks.
  # If none are specified, the node's primary interface will be used for management, cluster and storage networking.
  # To move the cluster and storage networks to a different interface than management, specify all three interfaces to use here.
  # NOTE: The cluster and storage networks need to be on the same interface.
  *adsNetworkInterfaces:*
    *managementInterface: "<mgmt_interface_name>"*
    *clusterInterface: "<cluster_and_storage_interface_name>"*
    *storageInterface: "<cluster_and_storage_interface_name>"*
  # [Optional] Provide a monitoring config to be used to setup/configure a monitoring agent.
 *# monitoringConfig:*
   *# namespace: "netapp-monitoring"*
   *# repo: "[YOUR REGISTRY]"*
  autoSupportConfig:
    autoUpload: true
    enabled: true
    coredumpUpload: false
    historyRetentionCount: 25
    destinationURL: "https://support.netapp.com/put/AsupPut"
    # ProxyURL defines the URL of the proxy with port to be used for AutoSupport bundle transfer
    *# proxyURL:*
    periodic:
      - schedule: "0 0 * * *"
        periodicconfig:
        - component:
            name: storage
            event: dailyMonitoring
          userMessage: Daily Monitoring Storage AutoSupport bundle
          nodes: all
        - component:
            name: controlplane
            event: daily
          userMessage: Daily Control Plane AutoSupport bundle
----
. kubectl apply を使用してクラスタを導入します
+
[listing]
----
kubectl apply -f ./astrads/manifests/astradscluster.yaml
----
. クラスタ作成処理が完了するまで数分待ってから、ポッドが実行されていることを確認します。
+
[listing]
----
kubectl get pods -n astrads-system
----
+
回答例：

+
[listing]
----
NAME                                              READY     STATUS    RESTARTS    AGE
astrads-cluster-controller-7c67cc7f7b-2jww2       1/1       Running   0           7h31m
astrads-deployment-support-788b859c65-2qjkn       3/3       Running   19          12d
astrads-ds-astrads-cluster-1ab0dbc-j9jzc          1/1       Running   0           5d2h
astrads-ds-astrads-cluster-1ab0dbc-k9wp8          1/1       Running   0           5d1h
astrads-ds-astrads-cluster-1ab0dbc-pwk42          1/1       Running   0           5d2h
astrads-ds-astrads-cluster-1ab0dbc-qhvc6          1/1       Running   0           8h
astrads-ds-nodeinfo-gcmj8                         1/1       Running   1           12d
astrads-ds-nodeinfo-j826x                         1/1       Running   3           12d
astrads-ds-nodeinfo-vdthh                         1/1       Running   3           12d
astrads-ds-nodeinfo-xwgsf                         1/1       Running   0           12d
astrads-ds-support-828vw                          2/2       Running   2           5d2h
astrads-ds-support-astrads-example-cluster-cfzts  2/2       Running   0           8h
astrads-ds-support-astrads-example-cluster-nzkkr  2/2       Running   15          7h49m
astrads-ds-support-astrads-example-cluster-xxbnp  2/2       Running   1           5d2h
astrads-license-controller-86c69f76bb-s6fb7       1/1       Running   0           8h
astrads-operator-79ff8fbb6d-vpz9m                 1/1       Running   0           8h
----
. クラスタの導入の進捗を確認します。
+
[listing]
----
kubectl get astradscluster -n astrads-system
----
+
回答例：

+
[listing]
----
NAME                        STATUS    VERSION      SERIAL NUMBER    MVIP       AGE

astrads-example-cluster     created   2022.05.0-X  e100000006       10.x.x.x   13m
----




=== 導入に関連するイベントを把握

クラスタの導入中に ' オペレーション・ステータスは ' ブランクから ' 進行中 ' から作成済みに変更する必要がありますクラスタの導入には約 8~10 分かかります。導入中にクラスタイベントを監視するには、次のいずれかのコマンドを実行します。

[listing]
----
kubectl get events --field-selector involvedObject.kind=AstraDSCluster -n astrads-system
----
[listing]
----
kubectl describe astradscluster <cluster name> -n astrads-system
----
導入時の主なイベントを次に示します。

|===
| イベント | メッセージと重要性 


| ControlPlaneNoDesSelected」を選択します | ADSクラスタに参加するための[number]コントロールプレーンノードが正常に選択されました。Astra Data Storeオペレータは、Astraデータストアクラスタを構築するために、CPU、メモリ、ストレージ、ネットワークを備えた十分なノードを特定しました。 


| ADSClusterCreateInProgress | Astraデータストアクラスタコントローラが、クラスタ作成処理を開始しました。 


| ADSClusterCreateSuccess | クラスタが作成されました。 
|===
クラスタのステータスが「 in progress 」に変わらない場合は、オペレータログでノード選択の詳細を確認します。

[listing]
----
kubectl logs -n astrads-system <astrads operator pod name>
----
クラスタのステータスが「in progress」のままになっている場合は、クラスタコントローラのログを確認します。

[listing]
----
kubectl logs -n astrads-system <astrads cluster controller pod name>
----


== Astra Control Centerを使用してAstraデータストアをインストールします

Astra Control Centerを使用してAstraデータストアを導入および使用するには、次の手順を実行します。

.必要なもの
* 確認が完了しました <<What you'll need,一般的なAstraデータストアの前提条件>>。
* Astra Control Centerをインストールしておきます。


.手順
. https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html#add-a-storage-backend["Astra Control Centerを使用してAstraデータストアを導入"^]。




== 次の手順

* * Kubernetesネイティブな導入環境とサードパーティのディストリビューション*：Astra Data Storeの導入を完了するには、追加の作業を実行します link:setup-ads.html["セットアップのタスク"]。
* * Astra Control Center *：Astra Control Centerを使用してAstraデータストアを導入したことがある場合、これらの手順に従う必要はありません link:../get-started/setup-ads.html#configure-astra-data-store-monitoring["セットアップのタスク"] その他の監視オプションを設定する場合を除きます。Astraデータストアの導入後、Astra Control Center UIを使用して次の作業を実行できます。
+
** https://docs.netapp.com/us-en/astra-control-center/use/monitor-protect.html["Astraデータストア資産の健常性を監視"^]。
** https://docs.netapp.com/us-en/astra-control-center/use/manage-backend.html["Astraデータストアのバックエンドストレージを管理"^]。
** https://docs.netapp.com/us-en/astra-control-center/use/view-dashboard.html["ノード、ディスク、永続的ボリューム要求（ PVC ）を監視"^]。



