---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: まずは、環境のサポート状況を確認します。 
---
= Astra データストアの要件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


まずは、Astraデータストアの要件を満たす環境であることを確認してください。

Astraデータストアは、ベアメタル環境とVMベース環境の両方をサポートしています。Astraデータストアクラスタは、4つ以上のワーカーノードで構成されるKubernetesクラスタで実行できます。Astra Data Storeソフトウェアは、同じKubernetesクラスタで実行されている他のアプリケーションと共存できます。

* <<Kubernetes worker node resources>>
* <<Hardware and software>>
* <<Networking>>
* <<Astra Trident>>
* <<Container Network Interfaces>>
* <<Licensing>>



NOTE: Astra Control CenterからAstraデータストアクラスタを管理する場合は、Astraデータストアクラスタがを満たしていることを確認します https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["Astra Control Center で管理するクラスタの要件"^] ここに記載されている要件に加えて、



== Kubernetesワーカーノードのリソース

Kubernetesクラスタ内の各ワーカーノード上のAstra Data Storeソフトウェアに割り当てる必要があるリソース要件は次のとおりです。

|===
| リソース | 最小（ Minimum ） | 最大 


| Astraデータストアクラスタのノード数 | 4. | 16 


| データドライブの数  a| 
* 3 （独立したキャッシュデバイスを使用）
* 4 （キャッシュデバイスがない場合）

| 14 


| データドライブのサイズ | 100GiB | 4TiB 未満 


| オプションのキャッシュデバイスの数 | 1（8GiBサイズ） | 該当なし 
|===
Astraデータストアでは、Kubernetesワーカーノードごとに次のvCPUとRAMの組み合わせをサポートしています。

* vCPU×9、38GiBのRAM
* vCPU×23、9GiBのRAM



NOTE: 書き込みパフォーマンスを最大限に高めるには、専用の耐久性、低レイテンシ、低容量キャッシュデバイスを構成する必要があります。

各ワーカーノードには、次の追加要件があります。

* 100GiB以上の空き容量がホストディスク（ブート）にあり、Astraデータストアのログファイルを格納できます。
* クラスタトラフィック、データトラフィック、および管理トラフィック用に、 10GbE 以上のネットワークインターフェイスが少なくとも 1 つ必要です。必要に応じて、 1GbE 以上のインターフェイスを追加で使用して管理トラフィックを分離できます。




== ハードウェアとソフトウェア：

Astra Data Storeソフトウェアは、次のハードウェアプラットフォーム、ソフトウェア、ストレージ構成で検証済みです。にアクセスします link:../support/get-help-ads.html["ネットアップコミュニティによるサポート"] Kubernetes クラスタの構成が異なる場合。



=== ハードウェアプラットフォーム

* Dell R640
* Dell R740
* HPE DL360
* HPE DL380
* Lenovo SR630
* Lenovo SR650



NOTE: VMベースの環境では、に互換性があると表示されているサーバを使用することもできます https://www.vmware.com/resources/compatibility/search.php["VMware Compatibility Guide 』を参照してください"^]。



=== ストレージ

Astraデータストアは、SATA、SAS、NVMe TLC SSDで検証済みです。

VMベースの環境では、仮想ディスクまたはパススルードライブとして提供されるドライブを使用できます。

[NOTE]
====
* ホストがハードウェア RAID コントローラの背後で SSD を使用している場合は、「パススルー」モードを使用するようにハードウェア RAID コントローラを設定します。
* 各ドライブのシリアル番号は一意である必要があります。VM 作成中に仮想マシンの詳細設定に 'disk.enableuuid=true' 属性を追加します


====


=== ソフトウェア

* ハイパーバイザー：Astraデータストアは、vSphere 7.0を使用したVMwareベースのVM環境で検証済みです。KVMベースの導入はAstraデータストアではサポートされていません。
* Astraデータストアは、次のホストオペレーティングシステムで検証済みです。
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2 の場合
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS (RHCS)
** CentOS 8
** Ubuntu 20.04


* Astraデータストアは、以下のKubernetesディストリビューションで検証済みです。
+
** Red Hat OpenShift 4.6～4.9
** Google Anthos 1.8～1.10
** Kubernetes 1.20～1.23
** Rancher RKE 1.3.3





NOTE: Astraデータストアには、ストレージのプロビジョニングとオーケストレーションを行うAstra Tridentが必要Tridentバージョン21.10.1～22.04がサポートされています。を参照してください link:setup-ads.html#install-astra-trident["Astra Trident のインストール手順"]。



== ネットワーキング

AstraデータストアのMVIP用にクラスタごとに1つのIPアドレスが必要MIP と同じサブネット内の未使用の IP アドレスまたは未設定の IP アドレスを指定する必要があります。Astraデータストア管理インターフェイスは、Kubernetesノードの管理インターフェイスと同じである必要があります。

また、次の表に示すように各ノードを設定することもできます。


NOTE: この表では、 MIP ：管理 IP アドレス CIP ：クラスタ IP アドレス MVIP ：管理仮想 IP アドレスの略語を使用しています

|===
| 設定 | IP アドレスが必要です 


| ノードごとに 1 つのネットワークインターフェイス  a| 
* ノードごとに 2 つ：
+
** MIP/CIP ：ノードごとに管理インターフェイスに設定済みの IP アドレスが 1 つあります
** データ IP ： MIP と同じサブネットに含まれる、ノードごとに未使用の IP アドレスまたは未設定の IP アドレスの 1 つ






| ノードごとに 2 つのネットワークインターフェイス  a| 
* ノードあたり 3 本：
+
** mip ：ノードごとに管理インターフェイスで事前に設定された IP アドレスを 1 つ
** cip ： MIP とは異なるサブネット内のノードごとに、データインターフェイスに事前に設定された IP アドレスを 1 つだけ指定します
** データ IP ： CIP と同じサブネット内の各ノードに未使用または未設定の IP アドレスが 1 つあります




|===

NOTE: これらの構成では VLAN タグは使用されません。



=== ファイアウォールに関する考慮事項

ネットワークファイアウォールトラフィックフィルタリングを実行する環境では、次の表に示すポートおよびプロトコルへの着信トラフィックを許可するようにファイアウォールを設定する必要があります。[IP Address]列には、次の省略形が使用されます。

* mip：各ノードの管理インターフェイスのプライマリIPアドレス
* cip：各ノードのクラスタインターフェイスのプライマリIPアドレス
* DIP：ノードに設定された1つ以上のデータIPアドレス
* MVIP：1つのクラスタノードに設定された管理仮想IPアドレス


|===
| ポート/プロトコル | IP アドレス | 目的 | 注： 


| 111 TCP | ディップ | NFS | データIPは実行時にクラスタノード間で移動されます。各ノードで、すべてのデータIP（またはサブネット全体）に対してこのトラフィックを許可する必要があります。 


| 442/TCP | MIP | API |  


| 635 TCP | ディップ | NFS | データIPは実行時にクラスタノード間で移動されます。各ノードで、すべてのデータIP（またはサブネット全体）に対してこのトラフィックを許可する必要があります。 


| 2010/UDP | CIP（CIP） | クラスタ/ノード検出 | UDPポート2010との間で送受信されるユニキャストトラフィックとブロードキャストトラフィックの両方が含まれます（応答も含まれます）。 


| 2049 TCP | ディップ | NFS | データIPは実行時にクラスタノード間で移動されます。各ノードで、すべてのデータIP（またはサブネット全体）に対してこのトラフィックを許可する必要があります。 


| 2181-2183/TCP | CIP（CIP） | 分散通信 |  


| 2443/TCPの場合 | MIP | API |  


| 2443/TCPの場合 | MVIPの数 | API | MVIPアドレスは任意のクラスタノードでホストでき、必要に応じて実行時に再配置されます。 


| 4000-4006 /TCP | CIP（CIP） | クラスタ内RPC |  


| 4045-4046/TCP | ディップ | NFS | データIPは実行時にクラスタノード間で移動されます。各ノードで、すべてのデータIP（またはサブネット全体）に対してこのトラフィックを許可する必要があります。 


| 7700/TCP | CIP（CIP） | セッションマネージャ |  


| 9919/TCP | MIP | DMS API |  


| 9920/TCP | ディップ | DMS RESTサーバ |  


| ICMP | CIP + DIP | ノード内通信、ヘルスチェック | データIPは実行時にクラスタノード間で移動されます。各ノードで、すべてのデータIP（またはサブネット全体）に対してこのトラフィックを許可する必要があります。 
|===


== Astra Trident

Astraデータストアを利用するには、ストレージのプロビジョニングとオーケストレーションを行うために、アプリケーションのKubernetesクラスタがAstra Tridentを実行している必要があります。Tridentバージョン21.10.1～22.04がサポートされています。Astraデータストアは、として構成できます link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["ストレージバックエンド"] ネットアップの Trident で永続的ボリュームをプロビジョニング



== コンテナネットワークインターフェイス

Astraデータストアは、次のContainer Network Interface（CNI;コンテナネットワークインターフェイス）で検証済みです。

* RKEクラスタの場合はCalico
* バニラ Kubernetes クラスタ用 Calico および Weave Net CNII
* Red Hat OpenShift Container Platform （ OCP ）向け OpenShift SDN
* Google Anthos 向け Cilium


[NOTE]
====
* Cilium CNIを使用して導入されたAstraデータストアでは、HostPortサポート用のportmapプラグインが必要です。CNIチェイニングモードをイネーブルにするには、cilium-config configMapに「ctie-mode:portmap」を追加し、Ciliumポッドを再起動します。
* ファイアウォール対応の構成は、CalicoおよびOpenShiftのSDN NNIでのみサポートされます。


====


== ライセンス

Astraデータストアのすべての機能を有効にするには、有効なライセンスが必要です。

https://www.netapp.com/cloud-services/astra/data-store-form/["こちらから登録してください"^] からAstraデータストアライセンスを取得できます。ライセンスのダウンロード手順は、サインアップ後に送信されます。



== 次の手順

を表示します link:quick-start.html["クイックスタート"] 概要（ Overview ）：



== を参照してください。

link:capabilities.html["Astraデータストアの制限"]
