---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: astra, astra data store, control center, limitations, known limitations, interoperability 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


既知の制限事項は、製品のこのEarly Access Program（EAP；早期アクセスプログラム）リリースでサポートされていないプラットフォーム、デバイス、または機能、またはそれと正常に相互運用できない機能を示しています。



== Astra Data Store 2022.05 Early Access Program (EAP)リリース

このリリースには、次の既知の制限事項があります。これらの既知の制限事項をよく確認してください。



=== VMwareとの統合に関する制限事項

次の機能はサポートされません。

* VMワークフロー：
+
** テンプレートからのクローン作成を含めて、VMをクローニングします
** 以前にVMディスクを取り外したあとでVMディスクを接続する


* VVolレプリケーション
* VVolデータストアを削除します
* ファーストクラスディスク（FC）
* VMware vMotion
* リンクモードのvCenter Server
* コンプライアンスのアラートと通知
* vCenterとVASA Providerが複数ある構成
+
** vCenter構成ごとに1つのVASA Providerを使用できます


* ストレージポリシーベースの管理はVMレベルでのみ実行でき、VMの作成後は変更できません。




==== 複数のVMディスクを同時にサイズ変更することはできません

このリリースでは、一度に1つのディスクのサイズ変更のみが可能です。一度に複数のディスクのサイズを変更しようとすると、サイズ変更処理は最初のディスクに対してのみ実行されます。



== 詳細については、こちらをご覧ください

* link:../release-notes/known-issues.html["既知の問題"]

