---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。 
---
= 既知の問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


既知の問題は、このリリースの製品を正常に使用できない可能性のある問題を特定します。



== Astra Data Store 2202.05 Early Access Program (EAP)リリース

このリリースには、これらの既知の問題が含まれていこれらの既知の問題をよく確認してください。



=== ストレージバックエンドのタスクがvSphereに表示されません

既存のストレージバックエンドを使用するアクションやストレージバックエンドを削除するアクションが送信された場合、そのタスクはvSphere Clientの最近のタスクパネルに表示されません。



=== VMの作成時に追加のフォルダが作成されます

vSphereでVMを作成すると、データストア内のVMごとに1つのフォルダではなく、追加のフォルダが作成されることがあります。



=== Astra Plugin for VMware vSphereでフィルタリングされたビューに、断続的にデータが表示されないことがあります

仮想マシンのテーブル列フィルタでは、フィルタリングされたデータが除外されることがあります。フィルタ処理されたビューには、代わりにロードアイコンが表示されます。この問題を解決するには、別のビューに移動し、フィルタをリセットしてデータをもう一度表示します。



=== KubernetesワーカーノードのIPアドレスの制限

次のシナリオで、Astraデータストアクラスタの作成が失敗する。

. Kubernetesワーカーノードには、Astraデータストアに割り当てられていないインターフェイスでホストされているIPアドレスがあります。
. このIPアドレスは、Astraデータストアクラスタに割り当てられたクラスタ/データIPアドレスと同じサブネット内にあります。




== 詳細については、こちらをご覧ください

* link:../release-notes/known-limitations.html["既知の制限"]

