---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: astra, control center, limitations, known limitations, interoperability 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


ここでは、本製品のプレビューリリースでサポートされていないプラットフォーム、デバイス、または機能、またはこのリリースと正常に相互運用できない機能について記載します。これらの制限事項を慎重に確認してください



== 1 つ以上のノードを削除する機能はサポートされていません

Astra Data Store プレビューでは、障害が発生したノードの交換はサポートされていますが、ノード削除機能はサポートされていません。



== ドライブを追加または削除する機能はサポートされていません

Astra Data Store プレビューでは、障害が発生したドライブの交換はサポートされていますが、既存のクラスタに対するドライブの追加や削除はサポートされていません。



== Astra データストアのプレビュー機能は、ファイアウォールが有効になっている場合は検証されません

Astra データストアのプレビューでは、ホストのファイアウォールを無効にする必要があります。Calico HostEndpoint などの CNI ツールを使用してファイアウォールを有効にすることは検証されていません。



== アップグレードまたはパッチを更新する必要があります

Astra データストアプレビュー版は、本番環境のワークロード向けには提供されていません。



== Ubuntu ベースのベアメタルまたは VM パススルー環境には NVMe TLC SSD が必要です

この制限は、 RHEL 、 RHCOS 、 CentOS ベースの環境には適用されません。



== 詳細については、こちらをご覧ください

* link:../release-notes/known-issues.html["既知の問題"]

